// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_top,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=67,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=5807,HLS_SYN_LUT=4849,HLS_VERSION=2023_2}" *)

module top (
        ap_clk,
        ap_rst_n,
        m_axi_memA_AWVALID,
        m_axi_memA_AWREADY,
        m_axi_memA_AWADDR,
        m_axi_memA_AWID,
        m_axi_memA_AWLEN,
        m_axi_memA_AWSIZE,
        m_axi_memA_AWBURST,
        m_axi_memA_AWLOCK,
        m_axi_memA_AWCACHE,
        m_axi_memA_AWPROT,
        m_axi_memA_AWQOS,
        m_axi_memA_AWREGION,
        m_axi_memA_AWUSER,
        m_axi_memA_WVALID,
        m_axi_memA_WREADY,
        m_axi_memA_WDATA,
        m_axi_memA_WSTRB,
        m_axi_memA_WLAST,
        m_axi_memA_WID,
        m_axi_memA_WUSER,
        m_axi_memA_ARVALID,
        m_axi_memA_ARREADY,
        m_axi_memA_ARADDR,
        m_axi_memA_ARID,
        m_axi_memA_ARLEN,
        m_axi_memA_ARSIZE,
        m_axi_memA_ARBURST,
        m_axi_memA_ARLOCK,
        m_axi_memA_ARCACHE,
        m_axi_memA_ARPROT,
        m_axi_memA_ARQOS,
        m_axi_memA_ARREGION,
        m_axi_memA_ARUSER,
        m_axi_memA_RVALID,
        m_axi_memA_RREADY,
        m_axi_memA_RDATA,
        m_axi_memA_RLAST,
        m_axi_memA_RID,
        m_axi_memA_RUSER,
        m_axi_memA_RRESP,
        m_axi_memA_BVALID,
        m_axi_memA_BREADY,
        m_axi_memA_BRESP,
        m_axi_memA_BID,
        m_axi_memA_BUSER,
        m_axi_memQ_AWVALID,
        m_axi_memQ_AWREADY,
        m_axi_memQ_AWADDR,
        m_axi_memQ_AWID,
        m_axi_memQ_AWLEN,
        m_axi_memQ_AWSIZE,
        m_axi_memQ_AWBURST,
        m_axi_memQ_AWLOCK,
        m_axi_memQ_AWCACHE,
        m_axi_memQ_AWPROT,
        m_axi_memQ_AWQOS,
        m_axi_memQ_AWREGION,
        m_axi_memQ_AWUSER,
        m_axi_memQ_WVALID,
        m_axi_memQ_WREADY,
        m_axi_memQ_WDATA,
        m_axi_memQ_WSTRB,
        m_axi_memQ_WLAST,
        m_axi_memQ_WID,
        m_axi_memQ_WUSER,
        m_axi_memQ_ARVALID,
        m_axi_memQ_ARREADY,
        m_axi_memQ_ARADDR,
        m_axi_memQ_ARID,
        m_axi_memQ_ARLEN,
        m_axi_memQ_ARSIZE,
        m_axi_memQ_ARBURST,
        m_axi_memQ_ARLOCK,
        m_axi_memQ_ARCACHE,
        m_axi_memQ_ARPROT,
        m_axi_memQ_ARQOS,
        m_axi_memQ_ARREGION,
        m_axi_memQ_ARUSER,
        m_axi_memQ_RVALID,
        m_axi_memQ_RREADY,
        m_axi_memQ_RDATA,
        m_axi_memQ_RLAST,
        m_axi_memQ_RID,
        m_axi_memQ_RUSER,
        m_axi_memQ_RRESP,
        m_axi_memQ_BVALID,
        m_axi_memQ_BREADY,
        m_axi_memQ_BRESP,
        m_axi_memQ_BID,
        m_axi_memQ_BUSER,
        m_axi_memR_AWVALID,
        m_axi_memR_AWREADY,
        m_axi_memR_AWADDR,
        m_axi_memR_AWID,
        m_axi_memR_AWLEN,
        m_axi_memR_AWSIZE,
        m_axi_memR_AWBURST,
        m_axi_memR_AWLOCK,
        m_axi_memR_AWCACHE,
        m_axi_memR_AWPROT,
        m_axi_memR_AWQOS,
        m_axi_memR_AWREGION,
        m_axi_memR_AWUSER,
        m_axi_memR_WVALID,
        m_axi_memR_WREADY,
        m_axi_memR_WDATA,
        m_axi_memR_WSTRB,
        m_axi_memR_WLAST,
        m_axi_memR_WID,
        m_axi_memR_WUSER,
        m_axi_memR_ARVALID,
        m_axi_memR_ARREADY,
        m_axi_memR_ARADDR,
        m_axi_memR_ARID,
        m_axi_memR_ARLEN,
        m_axi_memR_ARSIZE,
        m_axi_memR_ARBURST,
        m_axi_memR_ARLOCK,
        m_axi_memR_ARCACHE,
        m_axi_memR_ARPROT,
        m_axi_memR_ARQOS,
        m_axi_memR_ARREGION,
        m_axi_memR_ARUSER,
        m_axi_memR_RVALID,
        m_axi_memR_RREADY,
        m_axi_memR_RDATA,
        m_axi_memR_RLAST,
        m_axi_memR_RID,
        m_axi_memR_RUSER,
        m_axi_memR_RRESP,
        m_axi_memR_BVALID,
        m_axi_memR_BREADY,
        m_axi_memR_BRESP,
        m_axi_memR_BID,
        m_axi_memR_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEMA_ID_WIDTH = 1;
parameter    C_M_AXI_MEMA_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEMA_DATA_WIDTH = 32;
parameter    C_M_AXI_MEMA_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEMA_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEMA_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEMA_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEMA_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEMA_USER_VALUE = 0;
parameter    C_M_AXI_MEMA_PROT_VALUE = 0;
parameter    C_M_AXI_MEMA_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEMQ_ID_WIDTH = 1;
parameter    C_M_AXI_MEMQ_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEMQ_DATA_WIDTH = 32;
parameter    C_M_AXI_MEMQ_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEMQ_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEMQ_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEMQ_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEMQ_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEMQ_USER_VALUE = 0;
parameter    C_M_AXI_MEMQ_PROT_VALUE = 0;
parameter    C_M_AXI_MEMQ_CACHE_VALUE = 3;
parameter    C_M_AXI_MEMR_ID_WIDTH = 1;
parameter    C_M_AXI_MEMR_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEMR_DATA_WIDTH = 32;
parameter    C_M_AXI_MEMR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEMR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEMR_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEMR_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEMR_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEMR_USER_VALUE = 0;
parameter    C_M_AXI_MEMR_PROT_VALUE = 0;
parameter    C_M_AXI_MEMR_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEMA_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEMQ_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEMR_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_memA_AWVALID;
input   m_axi_memA_AWREADY;
output  [C_M_AXI_MEMA_ADDR_WIDTH - 1:0] m_axi_memA_AWADDR;
output  [C_M_AXI_MEMA_ID_WIDTH - 1:0] m_axi_memA_AWID;
output  [7:0] m_axi_memA_AWLEN;
output  [2:0] m_axi_memA_AWSIZE;
output  [1:0] m_axi_memA_AWBURST;
output  [1:0] m_axi_memA_AWLOCK;
output  [3:0] m_axi_memA_AWCACHE;
output  [2:0] m_axi_memA_AWPROT;
output  [3:0] m_axi_memA_AWQOS;
output  [3:0] m_axi_memA_AWREGION;
output  [C_M_AXI_MEMA_AWUSER_WIDTH - 1:0] m_axi_memA_AWUSER;
output   m_axi_memA_WVALID;
input   m_axi_memA_WREADY;
output  [C_M_AXI_MEMA_DATA_WIDTH - 1:0] m_axi_memA_WDATA;
output  [C_M_AXI_MEMA_WSTRB_WIDTH - 1:0] m_axi_memA_WSTRB;
output   m_axi_memA_WLAST;
output  [C_M_AXI_MEMA_ID_WIDTH - 1:0] m_axi_memA_WID;
output  [C_M_AXI_MEMA_WUSER_WIDTH - 1:0] m_axi_memA_WUSER;
output   m_axi_memA_ARVALID;
input   m_axi_memA_ARREADY;
output  [C_M_AXI_MEMA_ADDR_WIDTH - 1:0] m_axi_memA_ARADDR;
output  [C_M_AXI_MEMA_ID_WIDTH - 1:0] m_axi_memA_ARID;
output  [7:0] m_axi_memA_ARLEN;
output  [2:0] m_axi_memA_ARSIZE;
output  [1:0] m_axi_memA_ARBURST;
output  [1:0] m_axi_memA_ARLOCK;
output  [3:0] m_axi_memA_ARCACHE;
output  [2:0] m_axi_memA_ARPROT;
output  [3:0] m_axi_memA_ARQOS;
output  [3:0] m_axi_memA_ARREGION;
output  [C_M_AXI_MEMA_ARUSER_WIDTH - 1:0] m_axi_memA_ARUSER;
input   m_axi_memA_RVALID;
output   m_axi_memA_RREADY;
input  [C_M_AXI_MEMA_DATA_WIDTH - 1:0] m_axi_memA_RDATA;
input   m_axi_memA_RLAST;
input  [C_M_AXI_MEMA_ID_WIDTH - 1:0] m_axi_memA_RID;
input  [C_M_AXI_MEMA_RUSER_WIDTH - 1:0] m_axi_memA_RUSER;
input  [1:0] m_axi_memA_RRESP;
input   m_axi_memA_BVALID;
output   m_axi_memA_BREADY;
input  [1:0] m_axi_memA_BRESP;
input  [C_M_AXI_MEMA_ID_WIDTH - 1:0] m_axi_memA_BID;
input  [C_M_AXI_MEMA_BUSER_WIDTH - 1:0] m_axi_memA_BUSER;
output   m_axi_memQ_AWVALID;
input   m_axi_memQ_AWREADY;
output  [C_M_AXI_MEMQ_ADDR_WIDTH - 1:0] m_axi_memQ_AWADDR;
output  [C_M_AXI_MEMQ_ID_WIDTH - 1:0] m_axi_memQ_AWID;
output  [7:0] m_axi_memQ_AWLEN;
output  [2:0] m_axi_memQ_AWSIZE;
output  [1:0] m_axi_memQ_AWBURST;
output  [1:0] m_axi_memQ_AWLOCK;
output  [3:0] m_axi_memQ_AWCACHE;
output  [2:0] m_axi_memQ_AWPROT;
output  [3:0] m_axi_memQ_AWQOS;
output  [3:0] m_axi_memQ_AWREGION;
output  [C_M_AXI_MEMQ_AWUSER_WIDTH - 1:0] m_axi_memQ_AWUSER;
output   m_axi_memQ_WVALID;
input   m_axi_memQ_WREADY;
output  [C_M_AXI_MEMQ_DATA_WIDTH - 1:0] m_axi_memQ_WDATA;
output  [C_M_AXI_MEMQ_WSTRB_WIDTH - 1:0] m_axi_memQ_WSTRB;
output   m_axi_memQ_WLAST;
output  [C_M_AXI_MEMQ_ID_WIDTH - 1:0] m_axi_memQ_WID;
output  [C_M_AXI_MEMQ_WUSER_WIDTH - 1:0] m_axi_memQ_WUSER;
output   m_axi_memQ_ARVALID;
input   m_axi_memQ_ARREADY;
output  [C_M_AXI_MEMQ_ADDR_WIDTH - 1:0] m_axi_memQ_ARADDR;
output  [C_M_AXI_MEMQ_ID_WIDTH - 1:0] m_axi_memQ_ARID;
output  [7:0] m_axi_memQ_ARLEN;
output  [2:0] m_axi_memQ_ARSIZE;
output  [1:0] m_axi_memQ_ARBURST;
output  [1:0] m_axi_memQ_ARLOCK;
output  [3:0] m_axi_memQ_ARCACHE;
output  [2:0] m_axi_memQ_ARPROT;
output  [3:0] m_axi_memQ_ARQOS;
output  [3:0] m_axi_memQ_ARREGION;
output  [C_M_AXI_MEMQ_ARUSER_WIDTH - 1:0] m_axi_memQ_ARUSER;
input   m_axi_memQ_RVALID;
output   m_axi_memQ_RREADY;
input  [C_M_AXI_MEMQ_DATA_WIDTH - 1:0] m_axi_memQ_RDATA;
input   m_axi_memQ_RLAST;
input  [C_M_AXI_MEMQ_ID_WIDTH - 1:0] m_axi_memQ_RID;
input  [C_M_AXI_MEMQ_RUSER_WIDTH - 1:0] m_axi_memQ_RUSER;
input  [1:0] m_axi_memQ_RRESP;
input   m_axi_memQ_BVALID;
output   m_axi_memQ_BREADY;
input  [1:0] m_axi_memQ_BRESP;
input  [C_M_AXI_MEMQ_ID_WIDTH - 1:0] m_axi_memQ_BID;
input  [C_M_AXI_MEMQ_BUSER_WIDTH - 1:0] m_axi_memQ_BUSER;
output   m_axi_memR_AWVALID;
input   m_axi_memR_AWREADY;
output  [C_M_AXI_MEMR_ADDR_WIDTH - 1:0] m_axi_memR_AWADDR;
output  [C_M_AXI_MEMR_ID_WIDTH - 1:0] m_axi_memR_AWID;
output  [7:0] m_axi_memR_AWLEN;
output  [2:0] m_axi_memR_AWSIZE;
output  [1:0] m_axi_memR_AWBURST;
output  [1:0] m_axi_memR_AWLOCK;
output  [3:0] m_axi_memR_AWCACHE;
output  [2:0] m_axi_memR_AWPROT;
output  [3:0] m_axi_memR_AWQOS;
output  [3:0] m_axi_memR_AWREGION;
output  [C_M_AXI_MEMR_AWUSER_WIDTH - 1:0] m_axi_memR_AWUSER;
output   m_axi_memR_WVALID;
input   m_axi_memR_WREADY;
output  [C_M_AXI_MEMR_DATA_WIDTH - 1:0] m_axi_memR_WDATA;
output  [C_M_AXI_MEMR_WSTRB_WIDTH - 1:0] m_axi_memR_WSTRB;
output   m_axi_memR_WLAST;
output  [C_M_AXI_MEMR_ID_WIDTH - 1:0] m_axi_memR_WID;
output  [C_M_AXI_MEMR_WUSER_WIDTH - 1:0] m_axi_memR_WUSER;
output   m_axi_memR_ARVALID;
input   m_axi_memR_ARREADY;
output  [C_M_AXI_MEMR_ADDR_WIDTH - 1:0] m_axi_memR_ARADDR;
output  [C_M_AXI_MEMR_ID_WIDTH - 1:0] m_axi_memR_ARID;
output  [7:0] m_axi_memR_ARLEN;
output  [2:0] m_axi_memR_ARSIZE;
output  [1:0] m_axi_memR_ARBURST;
output  [1:0] m_axi_memR_ARLOCK;
output  [3:0] m_axi_memR_ARCACHE;
output  [2:0] m_axi_memR_ARPROT;
output  [3:0] m_axi_memR_ARQOS;
output  [3:0] m_axi_memR_ARREGION;
output  [C_M_AXI_MEMR_ARUSER_WIDTH - 1:0] m_axi_memR_ARUSER;
input   m_axi_memR_RVALID;
output   m_axi_memR_RREADY;
input  [C_M_AXI_MEMR_DATA_WIDTH - 1:0] m_axi_memR_RDATA;
input   m_axi_memR_RLAST;
input  [C_M_AXI_MEMR_ID_WIDTH - 1:0] m_axi_memR_RID;
input  [C_M_AXI_MEMR_RUSER_WIDTH - 1:0] m_axi_memR_RUSER;
input  [1:0] m_axi_memR_RRESP;
input   m_axi_memR_BVALID;
output   m_axi_memR_BREADY;
input  [1:0] m_axi_memR_BRESP;
input  [C_M_AXI_MEMR_ID_WIDTH - 1:0] m_axi_memR_BID;
input  [C_M_AXI_MEMR_BUSER_WIDTH - 1:0] m_axi_memR_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] A_DRAM;
wire   [63:0] Q_DRAM;
wire   [63:0] R_DRAM;
reg    memA_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    memQ_blk_n_AW;
wire    ap_CS_fsm_state17;
reg    memQ_blk_n_B;
wire    ap_CS_fsm_state24;
reg    memR_blk_n_AW;
reg    memR_blk_n_B;
reg   [61:0] trunc_ln_reg_1244;
reg   [61:0] trunc_ln2_reg_1250;
reg   [61:0] trunc_ln66_1_reg_1256;
wire   [31:0] grp_fu_524_p2;
reg   [31:0] Q_out_0_4_reg_1279;
wire    ap_CS_fsm_state15;
wire   [31:0] grp_fu_529_p2;
reg   [31:0] Q_out_1_5_reg_1284;
wire   [31:0] grp_fu_534_p2;
reg   [31:0] Q_out_2_6_reg_1289;
wire   [31:0] grp_fu_539_p2;
reg   [31:0] Q_out_3_7_reg_1294;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_done;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_idle;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_ready;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWVALID;
wire   [63:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWADDR;
wire   [0:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWID;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWLEN;
wire   [2:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWSIZE;
wire   [1:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWBURST;
wire   [1:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWLOCK;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWCACHE;
wire   [2:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWPROT;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWQOS;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWREGION;
wire   [0:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWUSER;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WVALID;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WDATA;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WSTRB;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WLAST;
wire   [0:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WID;
wire   [0:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WUSER;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARVALID;
wire   [63:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARADDR;
wire   [0:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARID;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARLEN;
wire   [2:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARSIZE;
wire   [1:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARBURST;
wire   [1:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARLOCK;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARCACHE;
wire   [2:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARPROT;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARQOS;
wire   [3:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARREGION;
wire   [0:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARUSER;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_RREADY;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_BREADY;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_load56_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_load56_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_load50_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_load50_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_load44_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_load44_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out1;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out1_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out2;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out2_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out3;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out3_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out4;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out4_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out5;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out5_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_3_load38_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_3_load38_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_3_load32_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_3_load32_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_3_load26_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_3_load26_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out6;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out6_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out7;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out7_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out8;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out8_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out9;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out9_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out10;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out10_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out11;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out11_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out12;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out12_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out13;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out13_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out14;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out14_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out15;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out15_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out16;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out16_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out17;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out17_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out18;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out18_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out19;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out19_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out20;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out20_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out21;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out21_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_3_load22_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_3_load22_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_2_load18_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_2_load18_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_1_load14_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_1_load14_out_ap_vld;
wire   [31:0] grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_load10_out;
wire    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_load10_out_ap_vld;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_idle;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_ready;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out1;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out1_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out2;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out2_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out3;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out3_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out4;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out4_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out5;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out5_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out6;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out6_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out7;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out7_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out8;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out8_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out9;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out9_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out10;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out10_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out11;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out11_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out12;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out12_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out13;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out13_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out14;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out14_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out15;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out15_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out16;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out16_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out17;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out17_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out18;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out18_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out19;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out19_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out20;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out20_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out21;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out21_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out22;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out22_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out23;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out23_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out24;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out24_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out25;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out25_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out26;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out26_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out27;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out27_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out28;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out28_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out29;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out29_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out30;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out30_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out31;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out31_ap_vld;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_din0;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_din1;
wire   [1:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_opcode;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_ce;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_din0;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_din1;
wire   [1:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_opcode;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_ce;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_din0;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_din1;
wire   [1:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_opcode;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_ce;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_din0;
wire   [31:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_din1;
wire   [1:0] grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_opcode;
wire    grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_ce;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_done;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_idle;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_ready;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWVALID;
wire   [63:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWADDR;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWID;
wire   [31:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWLEN;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWSIZE;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWBURST;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWLOCK;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWCACHE;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWPROT;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWQOS;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWREGION;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWUSER;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WVALID;
wire   [31:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WDATA;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WSTRB;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WLAST;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WID;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WUSER;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARVALID;
wire   [63:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARADDR;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARID;
wire   [31:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARLEN;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARSIZE;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARBURST;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARLOCK;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARCACHE;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARPROT;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARQOS;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARREGION;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARUSER;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_RREADY;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_BREADY;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWVALID;
wire   [63:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWADDR;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWID;
wire   [31:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWLEN;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWSIZE;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWBURST;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWLOCK;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWCACHE;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWPROT;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWQOS;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWREGION;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWUSER;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WVALID;
wire   [31:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WDATA;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WSTRB;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WLAST;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WID;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WUSER;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARVALID;
wire   [63:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARADDR;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARID;
wire   [31:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARLEN;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARSIZE;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARBURST;
wire   [1:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARLOCK;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARCACHE;
wire   [2:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARPROT;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARQOS;
wire   [3:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARREGION;
wire   [0:0] grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARUSER;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_RREADY;
wire    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_BREADY;
wire    memA_AWREADY;
wire    memA_WREADY;
reg    memA_ARVALID;
wire    memA_ARREADY;
reg   [63:0] memA_ARADDR;
reg   [31:0] memA_ARLEN;
wire    memA_RVALID;
reg    memA_RREADY;
wire   [31:0] memA_RDATA;
wire   [8:0] memA_RFIFONUM;
wire    memA_BVALID;
reg    memQ_AWVALID;
wire    memQ_AWREADY;
reg   [63:0] memQ_AWADDR;
reg   [31:0] memQ_AWLEN;
reg    memQ_WVALID;
wire    memQ_WREADY;
wire    memQ_ARREADY;
wire    memQ_RVALID;
wire   [31:0] memQ_RDATA;
wire   [8:0] memQ_RFIFONUM;
wire    memQ_BVALID;
reg    memQ_BREADY;
reg    memR_AWVALID;
wire    memR_AWREADY;
reg   [63:0] memR_AWADDR;
reg   [31:0] memR_AWLEN;
reg    memR_WVALID;
wire    memR_WREADY;
wire    memR_ARREADY;
wire    memR_RVALID;
wire   [31:0] memR_RDATA;
wire   [8:0] memR_RFIFONUM;
wire    memR_BVALID;
reg    memR_BREADY;
reg    grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start_reg;
wire    ap_CS_fsm_state16;
reg    grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire  signed [63:0] sext_ln39_fu_574_p1;
wire  signed [63:0] sext_ln66_fu_712_p1;
wire  signed [63:0] sext_ln66_1_fu_722_p1;
reg    ap_block_state17_io;
reg    ap_block_state24;
wire    ap_CS_fsm_state12;
reg   [31:0] grp_fu_524_p0;
reg   [31:0] grp_fu_524_p1;
reg   [31:0] grp_fu_529_p0;
reg   [31:0] grp_fu_529_p1;
reg   [31:0] grp_fu_534_p0;
reg   [31:0] grp_fu_534_p1;
reg   [31:0] grp_fu_539_p0;
reg   [31:0] grp_fu_539_p1;
reg    grp_fu_524_ce;
reg    grp_fu_529_ce;
reg    grp_fu_534_ce;
reg    grp_fu_539_ce;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start_reg = 1'b0;
#0 grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start_reg = 1'b0;
#0 grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start_reg = 1'b0;
end

top_top_Pipeline_READ_INIT_VITIS_LOOP_40_1 grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start),
    .ap_done(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_done),
    .ap_idle(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_idle),
    .ap_ready(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_ready),
    .m_axi_memA_AWVALID(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWVALID),
    .m_axi_memA_AWREADY(1'b0),
    .m_axi_memA_AWADDR(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWADDR),
    .m_axi_memA_AWID(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWID),
    .m_axi_memA_AWLEN(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWLEN),
    .m_axi_memA_AWSIZE(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWSIZE),
    .m_axi_memA_AWBURST(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWBURST),
    .m_axi_memA_AWLOCK(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWLOCK),
    .m_axi_memA_AWCACHE(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWCACHE),
    .m_axi_memA_AWPROT(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWPROT),
    .m_axi_memA_AWQOS(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWQOS),
    .m_axi_memA_AWREGION(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWREGION),
    .m_axi_memA_AWUSER(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_AWUSER),
    .m_axi_memA_WVALID(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WVALID),
    .m_axi_memA_WREADY(1'b0),
    .m_axi_memA_WDATA(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WDATA),
    .m_axi_memA_WSTRB(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WSTRB),
    .m_axi_memA_WLAST(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WLAST),
    .m_axi_memA_WID(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WID),
    .m_axi_memA_WUSER(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_WUSER),
    .m_axi_memA_ARVALID(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARVALID),
    .m_axi_memA_ARREADY(memA_ARREADY),
    .m_axi_memA_ARADDR(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARADDR),
    .m_axi_memA_ARID(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARID),
    .m_axi_memA_ARLEN(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARLEN),
    .m_axi_memA_ARSIZE(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARSIZE),
    .m_axi_memA_ARBURST(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARBURST),
    .m_axi_memA_ARLOCK(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARLOCK),
    .m_axi_memA_ARCACHE(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARCACHE),
    .m_axi_memA_ARPROT(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARPROT),
    .m_axi_memA_ARQOS(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARQOS),
    .m_axi_memA_ARREGION(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARREGION),
    .m_axi_memA_ARUSER(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARUSER),
    .m_axi_memA_RVALID(memA_RVALID),
    .m_axi_memA_RREADY(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_RREADY),
    .m_axi_memA_RDATA(memA_RDATA),
    .m_axi_memA_RLAST(1'b0),
    .m_axi_memA_RID(1'd0),
    .m_axi_memA_RFIFONUM(memA_RFIFONUM),
    .m_axi_memA_RUSER(1'd0),
    .m_axi_memA_RRESP(2'd0),
    .m_axi_memA_BVALID(1'b0),
    .m_axi_memA_BREADY(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_BREADY),
    .m_axi_memA_BRESP(2'd0),
    .m_axi_memA_BID(1'd0),
    .m_axi_memA_BUSER(1'd0),
    .sext_ln39(trunc_ln_reg_1244),
    .Q_2_load56_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_load56_out),
    .Q_2_load56_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_load56_out_ap_vld),
    .Q_1_load50_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_load50_out),
    .Q_1_load50_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_load50_out_ap_vld),
    .Q_3_load44_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_load44_out),
    .Q_3_load44_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_load44_out_ap_vld),
    .p_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out),
    .p_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out_ap_vld),
    .p_out1(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out1),
    .p_out1_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out1_ap_vld),
    .p_out2(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out2),
    .p_out2_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out2_ap_vld),
    .p_out3(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out3),
    .p_out3_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out3_ap_vld),
    .p_out4(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out4),
    .p_out4_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out4_ap_vld),
    .p_out5(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out5),
    .p_out5_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out5_ap_vld),
    .Q_1_3_load38_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_3_load38_out),
    .Q_1_3_load38_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_3_load38_out_ap_vld),
    .Q_0_3_load32_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_3_load32_out),
    .Q_0_3_load32_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_3_load32_out_ap_vld),
    .Q_2_3_load26_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_3_load26_out),
    .Q_2_3_load26_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_3_load26_out_ap_vld),
    .p_out6(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out6),
    .p_out6_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out6_ap_vld),
    .p_out7(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out7),
    .p_out7_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out7_ap_vld),
    .p_out8(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out8),
    .p_out8_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out8_ap_vld),
    .p_out9(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out9),
    .p_out9_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out9_ap_vld),
    .p_out10(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out10),
    .p_out10_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out10_ap_vld),
    .p_out11(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out11),
    .p_out11_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out11_ap_vld),
    .p_out12(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out12),
    .p_out12_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out12_ap_vld),
    .p_out13(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out13),
    .p_out13_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out13_ap_vld),
    .p_out14(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out14),
    .p_out14_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out14_ap_vld),
    .p_out15(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out15),
    .p_out15_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out15_ap_vld),
    .p_out16(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out16),
    .p_out16_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out16_ap_vld),
    .p_out17(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out17),
    .p_out17_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out17_ap_vld),
    .p_out18(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out18),
    .p_out18_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out18_ap_vld),
    .p_out19(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out19),
    .p_out19_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out19_ap_vld),
    .p_out20(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out20),
    .p_out20_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out20_ap_vld),
    .p_out21(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out21),
    .p_out21_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out21_ap_vld),
    .Q_3_3_load22_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_3_load22_out),
    .Q_3_3_load22_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_3_load22_out_ap_vld),
    .Q_2_2_load18_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_2_load18_out),
    .Q_2_2_load18_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_2_load18_out_ap_vld),
    .Q_1_1_load14_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_1_load14_out),
    .Q_1_1_load14_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_1_load14_out_ap_vld),
    .Q_0_load10_out(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_load10_out),
    .Q_0_load10_out_ap_vld(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_load10_out_ap_vld)
);

top_top_Pipeline_DUMMY_STAGE grp_top_Pipeline_DUMMY_STAGE_fu_412(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start),
    .ap_done(grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done),
    .ap_idle(grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_idle),
    .ap_ready(grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_ready),
    .Q_out_3_7(Q_out_3_7_reg_1294),
    .Q_out_2_6(Q_out_2_6_reg_1289),
    .p_reload140(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out9),
    .p_reload139(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out8),
    .p_reload138(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out7),
    .p_reload137(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out6),
    .Q_out_1_5(Q_out_1_5_reg_1284),
    .p_reload144(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out13),
    .p_reload143(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out12),
    .p_reload142(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out11),
    .p_reload141(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out10),
    .Q_out_0_4(Q_out_0_4_reg_1279),
    .p_reload148(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out17),
    .p_reload147(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out16),
    .p_reload146(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out15),
    .p_reload145(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out14),
    .p_reload152(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out21),
    .p_reload151(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out20),
    .p_reload150(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out19),
    .p_reload149(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out18),
    .Q_1_load50_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_load50_out),
    .Q_3_load44_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_load44_out),
    .Q_2_load56_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_load56_out),
    .p_reload133(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out2),
    .Q_1_1_load14_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_1_load14_out),
    .p_reload132(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out1),
    .p_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out),
    .p_reload136(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out5),
    .p_reload135(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out4),
    .Q_2_2_load18_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_2_load18_out),
    .p_reload134(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_p_out3),
    .Q_0_3_load32_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_3_load32_out),
    .Q_2_3_load26_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_3_load26_out),
    .Q_1_3_load38_reload(grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_3_load38_out),
    .p_out(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out),
    .p_out_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out_ap_vld),
    .p_out1(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out1),
    .p_out1_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out1_ap_vld),
    .p_out2(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out2),
    .p_out2_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out2_ap_vld),
    .p_out3(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out3),
    .p_out3_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out3_ap_vld),
    .p_out4(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out4),
    .p_out4_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out4_ap_vld),
    .p_out5(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out5),
    .p_out5_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out5_ap_vld),
    .p_out6(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out6),
    .p_out6_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out6_ap_vld),
    .p_out7(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out7),
    .p_out7_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out7_ap_vld),
    .p_out8(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out8),
    .p_out8_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out8_ap_vld),
    .p_out9(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out9),
    .p_out9_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out9_ap_vld),
    .p_out10(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out10),
    .p_out10_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out10_ap_vld),
    .p_out11(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out11),
    .p_out11_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out11_ap_vld),
    .p_out12(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out12),
    .p_out12_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out12_ap_vld),
    .p_out13(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out13),
    .p_out13_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out13_ap_vld),
    .p_out14(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out14),
    .p_out14_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out14_ap_vld),
    .p_out15(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out15),
    .p_out15_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out15_ap_vld),
    .p_out16(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out16),
    .p_out16_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out16_ap_vld),
    .p_out17(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out17),
    .p_out17_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out17_ap_vld),
    .p_out18(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out18),
    .p_out18_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out18_ap_vld),
    .p_out19(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out19),
    .p_out19_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out19_ap_vld),
    .p_out20(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out20),
    .p_out20_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out20_ap_vld),
    .p_out21(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out21),
    .p_out21_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out21_ap_vld),
    .p_out22(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out22),
    .p_out22_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out22_ap_vld),
    .p_out23(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out23),
    .p_out23_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out23_ap_vld),
    .p_out24(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out24),
    .p_out24_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out24_ap_vld),
    .p_out25(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out25),
    .p_out25_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out25_ap_vld),
    .p_out26(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out26),
    .p_out26_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out26_ap_vld),
    .p_out27(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out27),
    .p_out27_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out27_ap_vld),
    .p_out28(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out28),
    .p_out28_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out28_ap_vld),
    .p_out29(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out29),
    .p_out29_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out29_ap_vld),
    .p_out30(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out30),
    .p_out30_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out30_ap_vld),
    .p_out31(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out31),
    .p_out31_ap_vld(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out31_ap_vld),
    .grp_fu_524_p_din0(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_din0),
    .grp_fu_524_p_din1(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_din1),
    .grp_fu_524_p_opcode(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_opcode),
    .grp_fu_524_p_dout0(grp_fu_524_p2),
    .grp_fu_524_p_ce(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_ce),
    .grp_fu_529_p_din0(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_din0),
    .grp_fu_529_p_din1(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_din1),
    .grp_fu_529_p_opcode(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_opcode),
    .grp_fu_529_p_dout0(grp_fu_529_p2),
    .grp_fu_529_p_ce(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_ce),
    .grp_fu_534_p_din0(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_din0),
    .grp_fu_534_p_din1(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_din1),
    .grp_fu_534_p_opcode(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_opcode),
    .grp_fu_534_p_dout0(grp_fu_534_p2),
    .grp_fu_534_p_ce(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_ce),
    .grp_fu_539_p_din0(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_din0),
    .grp_fu_539_p_din1(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_din1),
    .grp_fu_539_p_opcode(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_opcode),
    .grp_fu_539_p_dout0(grp_fu_539_p2),
    .grp_fu_539_p_ce(grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_ce)
);

top_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3 grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start),
    .ap_done(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_done),
    .ap_idle(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_idle),
    .ap_ready(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_ready),
    .m_axi_memQ_AWVALID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWVALID),
    .m_axi_memQ_AWREADY(memQ_AWREADY),
    .m_axi_memQ_AWADDR(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWADDR),
    .m_axi_memQ_AWID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWID),
    .m_axi_memQ_AWLEN(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWLEN),
    .m_axi_memQ_AWSIZE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWSIZE),
    .m_axi_memQ_AWBURST(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWBURST),
    .m_axi_memQ_AWLOCK(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWLOCK),
    .m_axi_memQ_AWCACHE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWCACHE),
    .m_axi_memQ_AWPROT(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWPROT),
    .m_axi_memQ_AWQOS(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWQOS),
    .m_axi_memQ_AWREGION(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWREGION),
    .m_axi_memQ_AWUSER(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWUSER),
    .m_axi_memQ_WVALID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WVALID),
    .m_axi_memQ_WREADY(memQ_WREADY),
    .m_axi_memQ_WDATA(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WDATA),
    .m_axi_memQ_WSTRB(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WSTRB),
    .m_axi_memQ_WLAST(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WLAST),
    .m_axi_memQ_WID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WID),
    .m_axi_memQ_WUSER(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WUSER),
    .m_axi_memQ_ARVALID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARVALID),
    .m_axi_memQ_ARREADY(1'b0),
    .m_axi_memQ_ARADDR(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARADDR),
    .m_axi_memQ_ARID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARID),
    .m_axi_memQ_ARLEN(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARLEN),
    .m_axi_memQ_ARSIZE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARSIZE),
    .m_axi_memQ_ARBURST(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARBURST),
    .m_axi_memQ_ARLOCK(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARLOCK),
    .m_axi_memQ_ARCACHE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARCACHE),
    .m_axi_memQ_ARPROT(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARPROT),
    .m_axi_memQ_ARQOS(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARQOS),
    .m_axi_memQ_ARREGION(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARREGION),
    .m_axi_memQ_ARUSER(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_ARUSER),
    .m_axi_memQ_RVALID(1'b0),
    .m_axi_memQ_RREADY(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_RREADY),
    .m_axi_memQ_RDATA(32'd0),
    .m_axi_memQ_RLAST(1'b0),
    .m_axi_memQ_RID(1'd0),
    .m_axi_memQ_RFIFONUM(9'd0),
    .m_axi_memQ_RUSER(1'd0),
    .m_axi_memQ_RRESP(2'd0),
    .m_axi_memQ_BVALID(memQ_BVALID),
    .m_axi_memQ_BREADY(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_BREADY),
    .m_axi_memQ_BRESP(2'd0),
    .m_axi_memQ_BID(1'd0),
    .m_axi_memQ_BUSER(1'd0),
    .m_axi_memR_AWVALID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWVALID),
    .m_axi_memR_AWREADY(memR_AWREADY),
    .m_axi_memR_AWADDR(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWADDR),
    .m_axi_memR_AWID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWID),
    .m_axi_memR_AWLEN(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWLEN),
    .m_axi_memR_AWSIZE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWSIZE),
    .m_axi_memR_AWBURST(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWBURST),
    .m_axi_memR_AWLOCK(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWLOCK),
    .m_axi_memR_AWCACHE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWCACHE),
    .m_axi_memR_AWPROT(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWPROT),
    .m_axi_memR_AWQOS(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWQOS),
    .m_axi_memR_AWREGION(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWREGION),
    .m_axi_memR_AWUSER(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWUSER),
    .m_axi_memR_WVALID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WVALID),
    .m_axi_memR_WREADY(memR_WREADY),
    .m_axi_memR_WDATA(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WDATA),
    .m_axi_memR_WSTRB(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WSTRB),
    .m_axi_memR_WLAST(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WLAST),
    .m_axi_memR_WID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WID),
    .m_axi_memR_WUSER(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WUSER),
    .m_axi_memR_ARVALID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARVALID),
    .m_axi_memR_ARREADY(1'b0),
    .m_axi_memR_ARADDR(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARADDR),
    .m_axi_memR_ARID(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARID),
    .m_axi_memR_ARLEN(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARLEN),
    .m_axi_memR_ARSIZE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARSIZE),
    .m_axi_memR_ARBURST(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARBURST),
    .m_axi_memR_ARLOCK(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARLOCK),
    .m_axi_memR_ARCACHE(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARCACHE),
    .m_axi_memR_ARPROT(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARPROT),
    .m_axi_memR_ARQOS(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARQOS),
    .m_axi_memR_ARREGION(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARREGION),
    .m_axi_memR_ARUSER(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_ARUSER),
    .m_axi_memR_RVALID(1'b0),
    .m_axi_memR_RREADY(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_RREADY),
    .m_axi_memR_RDATA(32'd0),
    .m_axi_memR_RLAST(1'b0),
    .m_axi_memR_RID(1'd0),
    .m_axi_memR_RFIFONUM(9'd0),
    .m_axi_memR_RUSER(1'd0),
    .m_axi_memR_RRESP(2'd0),
    .m_axi_memR_BVALID(memR_BVALID),
    .m_axi_memR_BREADY(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_BREADY),
    .m_axi_memR_BRESP(2'd0),
    .m_axi_memR_BID(1'd0),
    .m_axi_memR_BUSER(1'd0),
    .sext_ln66(trunc_ln2_reg_1250),
    .sext_ln66_1(trunc_ln66_1_reg_1256),
    .p_reload217(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out31),
    .p_reload216(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out30),
    .p_reload215(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out29),
    .p_reload214(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out28),
    .p_reload213(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out27),
    .p_reload212(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out26),
    .p_reload211(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out25),
    .p_reload210(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out24),
    .p_reload209(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out23),
    .p_reload208(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out22),
    .p_reload207(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out21),
    .p_reload206(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out20),
    .p_reload205(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out19),
    .p_reload204(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out18),
    .p_reload203(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out17),
    .p_reload202(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out16),
    .p_reload201(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out15),
    .p_reload200(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out14),
    .p_reload199(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out13),
    .p_reload198(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out12),
    .p_reload197(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out11),
    .p_reload196(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out10),
    .p_reload195(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out9),
    .p_reload194(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out8),
    .p_reload193(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out7),
    .p_reload192(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out6),
    .p_reload191(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out5),
    .p_reload190(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out4),
    .p_reload189(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out3),
    .p_reload188(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out2),
    .p_reload187(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out1),
    .p_reload186(grp_top_Pipeline_DUMMY_STAGE_fu_412_p_out)
);

top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A_DRAM(A_DRAM),
    .Q_DRAM(Q_DRAM),
    .R_DRAM(R_DRAM),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

top_memA_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEMA_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEMA_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEMA_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEMA_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEMA_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEMA_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEMA_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEMA_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEMA_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEMA_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEMA_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
memA_m_axi_U(
    .AWVALID(m_axi_memA_AWVALID),
    .AWREADY(m_axi_memA_AWREADY),
    .AWADDR(m_axi_memA_AWADDR),
    .AWID(m_axi_memA_AWID),
    .AWLEN(m_axi_memA_AWLEN),
    .AWSIZE(m_axi_memA_AWSIZE),
    .AWBURST(m_axi_memA_AWBURST),
    .AWLOCK(m_axi_memA_AWLOCK),
    .AWCACHE(m_axi_memA_AWCACHE),
    .AWPROT(m_axi_memA_AWPROT),
    .AWQOS(m_axi_memA_AWQOS),
    .AWREGION(m_axi_memA_AWREGION),
    .AWUSER(m_axi_memA_AWUSER),
    .WVALID(m_axi_memA_WVALID),
    .WREADY(m_axi_memA_WREADY),
    .WDATA(m_axi_memA_WDATA),
    .WSTRB(m_axi_memA_WSTRB),
    .WLAST(m_axi_memA_WLAST),
    .WID(m_axi_memA_WID),
    .WUSER(m_axi_memA_WUSER),
    .ARVALID(m_axi_memA_ARVALID),
    .ARREADY(m_axi_memA_ARREADY),
    .ARADDR(m_axi_memA_ARADDR),
    .ARID(m_axi_memA_ARID),
    .ARLEN(m_axi_memA_ARLEN),
    .ARSIZE(m_axi_memA_ARSIZE),
    .ARBURST(m_axi_memA_ARBURST),
    .ARLOCK(m_axi_memA_ARLOCK),
    .ARCACHE(m_axi_memA_ARCACHE),
    .ARPROT(m_axi_memA_ARPROT),
    .ARQOS(m_axi_memA_ARQOS),
    .ARREGION(m_axi_memA_ARREGION),
    .ARUSER(m_axi_memA_ARUSER),
    .RVALID(m_axi_memA_RVALID),
    .RREADY(m_axi_memA_RREADY),
    .RDATA(m_axi_memA_RDATA),
    .RLAST(m_axi_memA_RLAST),
    .RID(m_axi_memA_RID),
    .RUSER(m_axi_memA_RUSER),
    .RRESP(m_axi_memA_RRESP),
    .BVALID(m_axi_memA_BVALID),
    .BREADY(m_axi_memA_BREADY),
    .BRESP(m_axi_memA_BRESP),
    .BID(m_axi_memA_BID),
    .BUSER(m_axi_memA_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(memA_ARVALID),
    .I_ARREADY(memA_ARREADY),
    .I_ARADDR(memA_ARADDR),
    .I_ARLEN(memA_ARLEN),
    .I_RVALID(memA_RVALID),
    .I_RREADY(memA_RREADY),
    .I_RDATA(memA_RDATA),
    .I_RFIFONUM(memA_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(memA_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(memA_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(memA_BVALID),
    .I_BREADY(1'b0)
);

top_memQ_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEMQ_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEMQ_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEMQ_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEMQ_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEMQ_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEMQ_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEMQ_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEMQ_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEMQ_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEMQ_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEMQ_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
memQ_m_axi_U(
    .AWVALID(m_axi_memQ_AWVALID),
    .AWREADY(m_axi_memQ_AWREADY),
    .AWADDR(m_axi_memQ_AWADDR),
    .AWID(m_axi_memQ_AWID),
    .AWLEN(m_axi_memQ_AWLEN),
    .AWSIZE(m_axi_memQ_AWSIZE),
    .AWBURST(m_axi_memQ_AWBURST),
    .AWLOCK(m_axi_memQ_AWLOCK),
    .AWCACHE(m_axi_memQ_AWCACHE),
    .AWPROT(m_axi_memQ_AWPROT),
    .AWQOS(m_axi_memQ_AWQOS),
    .AWREGION(m_axi_memQ_AWREGION),
    .AWUSER(m_axi_memQ_AWUSER),
    .WVALID(m_axi_memQ_WVALID),
    .WREADY(m_axi_memQ_WREADY),
    .WDATA(m_axi_memQ_WDATA),
    .WSTRB(m_axi_memQ_WSTRB),
    .WLAST(m_axi_memQ_WLAST),
    .WID(m_axi_memQ_WID),
    .WUSER(m_axi_memQ_WUSER),
    .ARVALID(m_axi_memQ_ARVALID),
    .ARREADY(m_axi_memQ_ARREADY),
    .ARADDR(m_axi_memQ_ARADDR),
    .ARID(m_axi_memQ_ARID),
    .ARLEN(m_axi_memQ_ARLEN),
    .ARSIZE(m_axi_memQ_ARSIZE),
    .ARBURST(m_axi_memQ_ARBURST),
    .ARLOCK(m_axi_memQ_ARLOCK),
    .ARCACHE(m_axi_memQ_ARCACHE),
    .ARPROT(m_axi_memQ_ARPROT),
    .ARQOS(m_axi_memQ_ARQOS),
    .ARREGION(m_axi_memQ_ARREGION),
    .ARUSER(m_axi_memQ_ARUSER),
    .RVALID(m_axi_memQ_RVALID),
    .RREADY(m_axi_memQ_RREADY),
    .RDATA(m_axi_memQ_RDATA),
    .RLAST(m_axi_memQ_RLAST),
    .RID(m_axi_memQ_RID),
    .RUSER(m_axi_memQ_RUSER),
    .RRESP(m_axi_memQ_RRESP),
    .BVALID(m_axi_memQ_BVALID),
    .BREADY(m_axi_memQ_BREADY),
    .BRESP(m_axi_memQ_BRESP),
    .BID(m_axi_memQ_BID),
    .BUSER(m_axi_memQ_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(memQ_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(memQ_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(memQ_RDATA),
    .I_RFIFONUM(memQ_RFIFONUM),
    .I_AWVALID(memQ_AWVALID),
    .I_AWREADY(memQ_AWREADY),
    .I_AWADDR(memQ_AWADDR),
    .I_AWLEN(memQ_AWLEN),
    .I_WVALID(memQ_WVALID),
    .I_WREADY(memQ_WREADY),
    .I_WDATA(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WDATA),
    .I_WSTRB(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WSTRB),
    .I_BVALID(memQ_BVALID),
    .I_BREADY(memQ_BREADY)
);

top_memR_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEMR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEMR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEMR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEMR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEMR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEMR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEMR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEMR_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEMR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEMR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEMR_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
memR_m_axi_U(
    .AWVALID(m_axi_memR_AWVALID),
    .AWREADY(m_axi_memR_AWREADY),
    .AWADDR(m_axi_memR_AWADDR),
    .AWID(m_axi_memR_AWID),
    .AWLEN(m_axi_memR_AWLEN),
    .AWSIZE(m_axi_memR_AWSIZE),
    .AWBURST(m_axi_memR_AWBURST),
    .AWLOCK(m_axi_memR_AWLOCK),
    .AWCACHE(m_axi_memR_AWCACHE),
    .AWPROT(m_axi_memR_AWPROT),
    .AWQOS(m_axi_memR_AWQOS),
    .AWREGION(m_axi_memR_AWREGION),
    .AWUSER(m_axi_memR_AWUSER),
    .WVALID(m_axi_memR_WVALID),
    .WREADY(m_axi_memR_WREADY),
    .WDATA(m_axi_memR_WDATA),
    .WSTRB(m_axi_memR_WSTRB),
    .WLAST(m_axi_memR_WLAST),
    .WID(m_axi_memR_WID),
    .WUSER(m_axi_memR_WUSER),
    .ARVALID(m_axi_memR_ARVALID),
    .ARREADY(m_axi_memR_ARREADY),
    .ARADDR(m_axi_memR_ARADDR),
    .ARID(m_axi_memR_ARID),
    .ARLEN(m_axi_memR_ARLEN),
    .ARSIZE(m_axi_memR_ARSIZE),
    .ARBURST(m_axi_memR_ARBURST),
    .ARLOCK(m_axi_memR_ARLOCK),
    .ARCACHE(m_axi_memR_ARCACHE),
    .ARPROT(m_axi_memR_ARPROT),
    .ARQOS(m_axi_memR_ARQOS),
    .ARREGION(m_axi_memR_ARREGION),
    .ARUSER(m_axi_memR_ARUSER),
    .RVALID(m_axi_memR_RVALID),
    .RREADY(m_axi_memR_RREADY),
    .RDATA(m_axi_memR_RDATA),
    .RLAST(m_axi_memR_RLAST),
    .RID(m_axi_memR_RID),
    .RUSER(m_axi_memR_RUSER),
    .RRESP(m_axi_memR_RRESP),
    .BVALID(m_axi_memR_BVALID),
    .BREADY(m_axi_memR_BREADY),
    .BRESP(m_axi_memR_BRESP),
    .BID(m_axi_memR_BID),
    .BUSER(m_axi_memR_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(memR_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(memR_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(memR_RDATA),
    .I_RFIFONUM(memR_RFIFONUM),
    .I_AWVALID(memR_AWVALID),
    .I_AWREADY(memR_AWREADY),
    .I_AWADDR(memR_AWADDR),
    .I_AWLEN(memR_AWLEN),
    .I_WVALID(memR_WVALID),
    .I_WREADY(memR_WREADY),
    .I_WDATA(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WDATA),
    .I_WSTRB(grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WSTRB),
    .I_BVALID(memR_BVALID),
    .I_BREADY(memR_BREADY)
);

top_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U159(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_524_p0),
    .din1(grp_fu_524_p1),
    .ce(grp_fu_524_ce),
    .dout(grp_fu_524_p2)
);

top_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U160(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_529_p0),
    .din1(grp_fu_529_p1),
    .ce(grp_fu_529_ce),
    .dout(grp_fu_529_p2)
);

top_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U161(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_534_p0),
    .din1(grp_fu_534_p1),
    .ce(grp_fu_534_ce),
    .dout(grp_fu_534_p2)
);

top_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U162(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_539_p0),
    .din1(grp_fu_539_p1),
    .ce(grp_fu_539_ce),
    .dout(grp_fu_539_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start_reg <= 1'b1;
        end else if ((grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_ready == 1'b1)) begin
            grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start_reg <= 1'b1;
        end else if ((grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_ready == 1'b1)) begin
            grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start_reg <= 1'b1;
        end else if ((grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_ready == 1'b1)) begin
            grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        Q_out_0_4_reg_1279 <= grp_fu_524_p2;
        Q_out_1_5_reg_1284 <= grp_fu_529_p2;
        Q_out_2_6_reg_1289 <= grp_fu_534_p2;
        Q_out_3_7_reg_1294 <= grp_fu_539_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln2_reg_1250 <= {{Q_DRAM[63:2]}};
        trunc_ln66_1_reg_1256 <= {{R_DRAM[63:2]}};
        trunc_ln_reg_1244 <= {{A_DRAM[63:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0))) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state24)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((memA_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_524_ce = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_ce;
    end else begin
        grp_fu_524_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_524_p0 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_524_p0 = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_0_load10_out;
    end else begin
        grp_fu_524_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_524_p1 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_524_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_524_p1 = 32'd1065353216;
    end else begin
        grp_fu_524_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_529_ce = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_ce;
    end else begin
        grp_fu_529_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_529_p0 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_529_p0 = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_1_1_load14_out;
    end else begin
        grp_fu_529_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_529_p1 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_529_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_529_p1 = 32'd1065353216;
    end else begin
        grp_fu_529_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_534_ce = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_ce;
    end else begin
        grp_fu_534_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_534_p0 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_534_p0 = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_2_2_load18_out;
    end else begin
        grp_fu_534_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_534_p1 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_534_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_534_p1 = 32'd1065353216;
    end else begin
        grp_fu_534_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_539_ce = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_ce;
    end else begin
        grp_fu_539_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_539_p0 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_539_p0 = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_Q_3_3_load22_out;
    end else begin
        grp_fu_539_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_539_p1 = grp_top_Pipeline_DUMMY_STAGE_fu_412_grp_fu_539_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_539_p1 = 32'd1065353216;
    end else begin
        grp_fu_539_p1 = 'bx;
    end
end

always @ (*) begin
    if (((memA_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        memA_ARADDR = sext_ln39_fu_574_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        memA_ARADDR = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARADDR;
    end else begin
        memA_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((memA_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        memA_ARLEN = 32'd16;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        memA_ARLEN = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARLEN;
    end else begin
        memA_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((memA_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        memA_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        memA_ARVALID = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_ARVALID;
    end else begin
        memA_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        memA_RREADY = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_m_axi_memA_RREADY;
    end else begin
        memA_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        memA_blk_n_AR = m_axi_memA_ARREADY;
    end else begin
        memA_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        memQ_AWADDR = sext_ln66_fu_712_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memQ_AWADDR = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWADDR;
    end else begin
        memQ_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        memQ_AWLEN = 32'd16;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memQ_AWLEN = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWLEN;
    end else begin
        memQ_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        memQ_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memQ_AWVALID = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_AWVALID;
    end else begin
        memQ_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24))) begin
        memQ_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memQ_BREADY = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_BREADY;
    end else begin
        memQ_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memQ_WVALID = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memQ_WVALID;
    end else begin
        memQ_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        memQ_blk_n_AW = m_axi_memQ_AWREADY;
    end else begin
        memQ_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        memQ_blk_n_B = m_axi_memQ_BVALID;
    end else begin
        memQ_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        memR_AWADDR = sext_ln66_1_fu_722_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memR_AWADDR = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWADDR;
    end else begin
        memR_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        memR_AWLEN = 32'd16;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memR_AWLEN = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWLEN;
    end else begin
        memR_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        memR_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memR_AWVALID = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_AWVALID;
    end else begin
        memR_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24))) begin
        memR_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memR_BREADY = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_BREADY;
    end else begin
        memR_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        memR_WVALID = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_m_axi_memR_WVALID;
    end else begin
        memR_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        memR_blk_n_AW = m_axi_memR_AWREADY;
    end else begin
        memR_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        memR_blk_n_B = m_axi_memR_BVALID;
    end else begin
        memR_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((memA_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if ((~((1'b1 == ap_block_state17_io) | (grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (1'b0 == ap_block_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

always @ (*) begin
    ap_block_state17_io = ((memR_AWREADY == 1'b0) | (memQ_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state24 = ((memR_BVALID == 1'b0) | (memQ_BVALID == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start = grp_top_Pipeline_DUMMY_STAGE_fu_412_ap_start_reg;

assign grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start = grp_top_Pipeline_READ_INIT_VITIS_LOOP_40_1_fu_373_ap_start_reg;

assign grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start = grp_top_Pipeline_WRITE_BACK_VITIS_LOOP_69_3_fu_482_ap_start_reg;

assign sext_ln39_fu_574_p1 = $signed(trunc_ln_reg_1244);

assign sext_ln66_1_fu_722_p1 = $signed(trunc_ln66_1_reg_1256);

assign sext_ln66_fu_712_p1 = $signed(trunc_ln2_reg_1250);

endmodule //top
