// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_top_Pipeline_READ_INIT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty_106,
        empty_107,
        empty_108,
        empty_109,
        empty_110,
        empty_111,
        empty_112,
        empty_113,
        empty_114,
        empty_115,
        empty_116,
        empty_117,
        empty_118,
        empty_119,
        empty_120,
        empty,
        Q_2_load39_out,
        Q_2_load39_out_ap_vld,
        Q_1_load35_out,
        Q_1_load35_out_ap_vld,
        Q_3_load31_out,
        Q_3_load31_out_ap_vld,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        Q_1_3_load27_out,
        Q_1_3_load27_out_ap_vld,
        Q_0_3_load23_out,
        Q_0_3_load23_out_ap_vld,
        Q_2_3_load19_out,
        Q_2_3_load19_out_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_out9,
        p_out9_ap_vld,
        p_out10,
        p_out10_ap_vld,
        p_out11,
        p_out11_ap_vld,
        p_out12,
        p_out12_ap_vld,
        p_out13,
        p_out13_ap_vld,
        p_out14,
        p_out14_ap_vld,
        p_out15,
        p_out15_ap_vld,
        p_out16,
        p_out16_ap_vld,
        p_out17,
        p_out17_ap_vld,
        p_out18,
        p_out18_ap_vld,
        p_out19,
        p_out19_ap_vld,
        p_out20,
        p_out20_ap_vld,
        p_out21,
        p_out21_ap_vld,
        Q_3_3_load_out,
        Q_3_3_load_out_ap_vld,
        Q_2_2_load_out,
        Q_2_2_load_out_ap_vld,
        Q_1_1_load_out,
        Q_1_1_load_out_ap_vld,
        Q_0_load_out,
        Q_0_load_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] empty_106;
input  [31:0] empty_107;
input  [31:0] empty_108;
input  [31:0] empty_109;
input  [31:0] empty_110;
input  [31:0] empty_111;
input  [31:0] empty_112;
input  [31:0] empty_113;
input  [31:0] empty_114;
input  [31:0] empty_115;
input  [31:0] empty_116;
input  [31:0] empty_117;
input  [31:0] empty_118;
input  [31:0] empty_119;
input  [31:0] empty_120;
input  [31:0] empty;
output  [31:0] Q_2_load39_out;
output   Q_2_load39_out_ap_vld;
output  [31:0] Q_1_load35_out;
output   Q_1_load35_out_ap_vld;
output  [31:0] Q_3_load31_out;
output   Q_3_load31_out_ap_vld;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;
output  [31:0] p_out4;
output   p_out4_ap_vld;
output  [31:0] p_out5;
output   p_out5_ap_vld;
output  [31:0] Q_1_3_load27_out;
output   Q_1_3_load27_out_ap_vld;
output  [31:0] Q_0_3_load23_out;
output   Q_0_3_load23_out_ap_vld;
output  [31:0] Q_2_3_load19_out;
output   Q_2_3_load19_out_ap_vld;
output  [31:0] p_out6;
output   p_out6_ap_vld;
output  [31:0] p_out7;
output   p_out7_ap_vld;
output  [31:0] p_out8;
output   p_out8_ap_vld;
output  [31:0] p_out9;
output   p_out9_ap_vld;
output  [31:0] p_out10;
output   p_out10_ap_vld;
output  [31:0] p_out11;
output   p_out11_ap_vld;
output  [31:0] p_out12;
output   p_out12_ap_vld;
output  [31:0] p_out13;
output   p_out13_ap_vld;
output  [31:0] p_out14;
output   p_out14_ap_vld;
output  [31:0] p_out15;
output   p_out15_ap_vld;
output  [31:0] p_out16;
output   p_out16_ap_vld;
output  [31:0] p_out17;
output   p_out17_ap_vld;
output  [31:0] p_out18;
output   p_out18_ap_vld;
output  [31:0] p_out19;
output   p_out19_ap_vld;
output  [31:0] p_out20;
output   p_out20_ap_vld;
output  [31:0] p_out21;
output   p_out21_ap_vld;
output  [31:0] Q_3_3_load_out;
output   Q_3_3_load_out_ap_vld;
output  [31:0] Q_2_2_load_out;
output   Q_2_2_load_out_ap_vld;
output  [31:0] Q_1_1_load_out;
output   Q_1_1_load_out_ap_vld;
output  [31:0] Q_0_load_out;
output   Q_0_load_out_ap_vld;

reg ap_idle;
reg Q_2_load39_out_ap_vld;
reg Q_1_load35_out_ap_vld;
reg Q_3_load31_out_ap_vld;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg Q_1_3_load27_out_ap_vld;
reg Q_0_3_load23_out_ap_vld;
reg Q_2_3_load19_out_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_out9_ap_vld;
reg p_out10_ap_vld;
reg p_out11_ap_vld;
reg p_out12_ap_vld;
reg p_out13_ap_vld;
reg p_out14_ap_vld;
reg p_out15_ap_vld;
reg p_out16_ap_vld;
reg p_out17_ap_vld;
reg p_out18_ap_vld;
reg p_out19_ap_vld;
reg p_out20_ap_vld;
reg p_out21_ap_vld;
reg Q_3_3_load_out_ap_vld;
reg Q_2_2_load_out_ap_vld;
reg Q_1_1_load_out_ap_vld;
reg Q_0_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln39_fu_602_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_fu_142;
wire   [2:0] add_ln39_fu_608_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_2;
reg   [31:0] Q_0_load_fu_146;
wire   [31:0] Q_0_4_fu_648_p3;
wire   [1:0] trunc_ln39_fu_614_p1;
reg   [31:0] Q_1_1_load_fu_150;
wire   [31:0] Q_0_5_fu_662_p3;
reg   [31:0] Q_2_2_load_fu_154;
wire   [31:0] Q_0_6_fu_676_p3;
reg   [31:0] Q_3_3_load_fu_158;
wire   [31:0] Q_0_fu_842_p3;
reg   [31:0] empty_126_fu_162;
wire   [31:0] R_0_fu_618_p11;
reg   [31:0] empty_127_fu_166;
reg   [31:0] empty_128_fu_170;
reg   [31:0] empty_129_fu_174;
reg   [31:0] empty_130_fu_178;
wire   [31:0] tmp_20_fu_684_p11;
reg   [31:0] empty_131_fu_182;
reg   [31:0] empty_132_fu_186;
reg   [31:0] empty_133_fu_190;
reg   [31:0] empty_134_fu_194;
wire   [31:0] tmp_21_fu_708_p11;
reg   [31:0] empty_135_fu_198;
reg   [31:0] empty_136_fu_202;
reg   [31:0] empty_137_fu_206;
reg   [31:0] empty_138_fu_210;
wire   [31:0] R_0_3_fu_732_p11;
reg   [31:0] empty_139_fu_214;
reg   [31:0] empty_140_fu_218;
reg   [31:0] empty_141_fu_222;
reg   [31:0] Q_2_3_load19_fu_226;
reg   [31:0] Q_0_3_load23_fu_230;
reg   [31:0] Q_1_3_load27_fu_234;
reg   [31:0] empty_142_fu_238;
reg   [31:0] empty_143_fu_242;
reg   [31:0] empty_144_fu_246;
reg   [31:0] empty_145_fu_250;
reg   [31:0] empty_146_fu_254;
reg   [31:0] empty_147_fu_258;
reg   [31:0] Q_3_load31_fu_262;
reg   [31:0] Q_1_load35_fu_266;
reg   [31:0] Q_2_load39_fu_270;
wire   [31:0] R_0_fu_618_p9;
wire   [0:0] icmp_ln46_fu_642_p2;
wire   [0:0] icmp_ln46_1_fu_656_p2;
wire   [0:0] icmp_ln46_2_fu_670_p2;
wire   [31:0] tmp_20_fu_684_p9;
wire   [31:0] tmp_21_fu_708_p9;
wire   [31:0] R_0_3_fu_732_p9;
wire   [0:0] icmp_ln46_3_fu_836_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire   [1:0] R_0_fu_618_p1;
wire   [1:0] R_0_fu_618_p3;
wire  signed [1:0] R_0_fu_618_p5;
wire  signed [1:0] R_0_fu_618_p7;
wire   [1:0] tmp_20_fu_684_p1;
wire   [1:0] tmp_20_fu_684_p3;
wire  signed [1:0] tmp_20_fu_684_p5;
wire  signed [1:0] tmp_20_fu_684_p7;
wire   [1:0] tmp_21_fu_708_p1;
wire   [1:0] tmp_21_fu_708_p3;
wire  signed [1:0] tmp_21_fu_708_p5;
wire  signed [1:0] tmp_21_fu_708_p7;
wire   [1:0] R_0_3_fu_732_p1;
wire   [1:0] R_0_3_fu_732_p3;
wire  signed [1:0] R_0_3_fu_732_p5;
wire  signed [1:0] R_0_3_fu_732_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_142 = 3'd0;
#0 Q_0_load_fu_146 = 32'd0;
#0 Q_1_1_load_fu_150 = 32'd0;
#0 Q_2_2_load_fu_154 = 32'd0;
#0 Q_3_3_load_fu_158 = 32'd0;
#0 empty_126_fu_162 = 32'd0;
#0 empty_127_fu_166 = 32'd0;
#0 empty_128_fu_170 = 32'd0;
#0 empty_129_fu_174 = 32'd0;
#0 empty_130_fu_178 = 32'd0;
#0 empty_131_fu_182 = 32'd0;
#0 empty_132_fu_186 = 32'd0;
#0 empty_133_fu_190 = 32'd0;
#0 empty_134_fu_194 = 32'd0;
#0 empty_135_fu_198 = 32'd0;
#0 empty_136_fu_202 = 32'd0;
#0 empty_137_fu_206 = 32'd0;
#0 empty_138_fu_210 = 32'd0;
#0 empty_139_fu_214 = 32'd0;
#0 empty_140_fu_218 = 32'd0;
#0 empty_141_fu_222 = 32'd0;
#0 Q_2_3_load19_fu_226 = 32'd0;
#0 Q_0_3_load23_fu_230 = 32'd0;
#0 Q_1_3_load27_fu_234 = 32'd0;
#0 empty_142_fu_238 = 32'd0;
#0 empty_143_fu_242 = 32'd0;
#0 empty_144_fu_246 = 32'd0;
#0 empty_145_fu_250 = 32'd0;
#0 empty_146_fu_254 = 32'd0;
#0 empty_147_fu_258 = 32'd0;
#0 Q_3_load31_fu_262 = 32'd0;
#0 Q_1_load35_fu_266 = 32'd0;
#0 Q_2_load39_fu_270 = 32'd0;
#0 ap_done_reg = 1'b0;
end

top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U1(
    .din0(empty_106),
    .din1(empty_107),
    .din2(empty_108),
    .din3(empty_109),
    .def(R_0_fu_618_p9),
    .sel(trunc_ln39_fu_614_p1),
    .dout(R_0_fu_618_p11)
);

top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2(
    .din0(empty_110),
    .din1(empty_111),
    .din2(empty_112),
    .din3(empty_113),
    .def(tmp_20_fu_684_p9),
    .sel(trunc_ln39_fu_614_p1),
    .dout(tmp_20_fu_684_p11)
);

top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U3(
    .din0(empty_114),
    .din1(empty_115),
    .din2(empty_116),
    .din3(empty_117),
    .def(tmp_21_fu_708_p9),
    .sel(trunc_ln39_fu_614_p1),
    .dout(tmp_21_fu_708_p11)
);

top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U4(
    .din0(empty_118),
    .din1(empty_119),
    .din2(empty_120),
    .din3(empty),
    .def(R_0_3_fu_732_p9),
    .sel(trunc_ln39_fu_614_p1),
    .dout(R_0_3_fu_732_p11)
);

top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln39_fu_602_p2 == 1'd0)) begin
            i_fu_142 <= add_ln39_fu_608_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_142 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_602_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln39_fu_614_p1 == 2'd0))) begin
        Q_0_3_load23_fu_230[29 : 23] <= Q_0_fu_842_p3[29 : 23];
        Q_0_load_fu_146[29 : 23] <= Q_0_4_fu_648_p3[29 : 23];
        empty_126_fu_162 <= R_0_fu_618_p11;
        empty_130_fu_178 <= tmp_20_fu_684_p11;
        empty_134_fu_194 <= tmp_21_fu_708_p11;
        empty_138_fu_210 <= R_0_3_fu_732_p11;
        empty_142_fu_238[29 : 23] <= Q_0_6_fu_676_p3[29 : 23];
        empty_145_fu_250[29 : 23] <= Q_0_5_fu_662_p3[29 : 23];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_602_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln39_fu_614_p1 == 2'd1))) begin
        Q_1_1_load_fu_150[29 : 23] <= Q_0_5_fu_662_p3[29 : 23];
        Q_1_3_load27_fu_234[29 : 23] <= Q_0_fu_842_p3[29 : 23];
        Q_1_load35_fu_266[29 : 23] <= Q_0_4_fu_648_p3[29 : 23];
        empty_127_fu_166 <= R_0_fu_618_p11;
        empty_131_fu_182 <= tmp_20_fu_684_p11;
        empty_135_fu_198 <= tmp_21_fu_708_p11;
        empty_139_fu_214 <= R_0_3_fu_732_p11;
        empty_143_fu_242[29 : 23] <= Q_0_6_fu_676_p3[29 : 23];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_602_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln39_fu_614_p1 == 2'd2))) begin
        Q_2_2_load_fu_154[29 : 23] <= Q_0_6_fu_676_p3[29 : 23];
        Q_2_3_load19_fu_226[29 : 23] <= Q_0_fu_842_p3[29 : 23];
        Q_2_load39_fu_270[29 : 23] <= Q_0_4_fu_648_p3[29 : 23];
        empty_128_fu_170 <= R_0_fu_618_p11;
        empty_132_fu_186 <= tmp_20_fu_684_p11;
        empty_136_fu_202 <= tmp_21_fu_708_p11;
        empty_140_fu_218 <= R_0_3_fu_732_p11;
        empty_146_fu_254[29 : 23] <= Q_0_5_fu_662_p3[29 : 23];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_602_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln39_fu_614_p1 == 2'd3))) begin
        Q_3_3_load_fu_158[29 : 23] <= Q_0_fu_842_p3[29 : 23];
        Q_3_load31_fu_262[29 : 23] <= Q_0_4_fu_648_p3[29 : 23];
        empty_129_fu_174 <= R_0_fu_618_p11;
        empty_133_fu_190 <= tmp_20_fu_684_p11;
        empty_137_fu_206 <= tmp_21_fu_708_p11;
        empty_141_fu_222 <= R_0_3_fu_732_p11;
        empty_144_fu_246[29 : 23] <= Q_0_6_fu_676_p3[29 : 23];
        empty_147_fu_258[29 : 23] <= Q_0_5_fu_662_p3[29 : 23];
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_0_3_load23_out_ap_vld = 1'b1;
    end else begin
        Q_0_3_load23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_0_load_out_ap_vld = 1'b1;
    end else begin
        Q_0_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_1_1_load_out_ap_vld = 1'b1;
    end else begin
        Q_1_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_1_3_load27_out_ap_vld = 1'b1;
    end else begin
        Q_1_3_load27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_1_load35_out_ap_vld = 1'b1;
    end else begin
        Q_1_load35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_2_2_load_out_ap_vld = 1'b1;
    end else begin
        Q_2_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_2_3_load19_out_ap_vld = 1'b1;
    end else begin
        Q_2_3_load19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_2_load39_out_ap_vld = 1'b1;
    end else begin
        Q_2_load39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_3_3_load_out_ap_vld = 1'b1;
    end else begin
        Q_3_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        Q_3_load31_out_ap_vld = 1'b1;
    end else begin
        Q_3_load31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_142;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out10_ap_vld = 1'b1;
    end else begin
        p_out10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out11_ap_vld = 1'b1;
    end else begin
        p_out11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out12_ap_vld = 1'b1;
    end else begin
        p_out12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out13_ap_vld = 1'b1;
    end else begin
        p_out13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out14_ap_vld = 1'b1;
    end else begin
        p_out14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out15_ap_vld = 1'b1;
    end else begin
        p_out15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out16_ap_vld = 1'b1;
    end else begin
        p_out16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out17_ap_vld = 1'b1;
    end else begin
        p_out17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out18_ap_vld = 1'b1;
    end else begin
        p_out18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out19_ap_vld = 1'b1;
    end else begin
        p_out19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out20_ap_vld = 1'b1;
    end else begin
        p_out20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out21_ap_vld = 1'b1;
    end else begin
        p_out21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out9_ap_vld = 1'b1;
    end else begin
        p_out9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_602_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Q_0_3_load23_out = Q_0_3_load23_fu_230;

assign Q_0_4_fu_648_p3 = ((icmp_ln46_fu_642_p2[0:0] == 1'b1) ? 32'd1065353216 : 32'd0);

assign Q_0_5_fu_662_p3 = ((icmp_ln46_1_fu_656_p2[0:0] == 1'b1) ? 32'd1065353216 : 32'd0);

assign Q_0_6_fu_676_p3 = ((icmp_ln46_2_fu_670_p2[0:0] == 1'b1) ? 32'd1065353216 : 32'd0);

assign Q_0_fu_842_p3 = ((icmp_ln46_3_fu_836_p2[0:0] == 1'b1) ? 32'd1065353216 : 32'd0);

assign Q_0_load_out = Q_0_load_fu_146;

assign Q_1_1_load_out = Q_1_1_load_fu_150;

assign Q_1_3_load27_out = Q_1_3_load27_fu_234;

assign Q_1_load35_out = Q_1_load35_fu_266;

assign Q_2_2_load_out = Q_2_2_load_fu_154;

assign Q_2_3_load19_out = Q_2_3_load19_fu_226;

assign Q_2_load39_out = Q_2_load39_fu_270;

assign Q_3_3_load_out = Q_3_3_load_fu_158;

assign Q_3_load31_out = Q_3_load31_fu_262;

assign R_0_3_fu_732_p9 = 'bx;

assign R_0_fu_618_p9 = 'bx;

assign add_ln39_fu_608_p2 = (ap_sig_allocacmp_i_2 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln39_fu_602_p2 = ((ap_sig_allocacmp_i_2 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_656_p2 = ((ap_sig_allocacmp_i_2 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln46_2_fu_670_p2 = ((ap_sig_allocacmp_i_2 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln46_3_fu_836_p2 = ((ap_sig_allocacmp_i_2 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_642_p2 = ((ap_sig_allocacmp_i_2 == 3'd0) ? 1'b1 : 1'b0);

assign p_out = empty_147_fu_258;

assign p_out1 = empty_146_fu_254;

assign p_out10 = empty_137_fu_206;

assign p_out11 = empty_136_fu_202;

assign p_out12 = empty_135_fu_198;

assign p_out13 = empty_134_fu_194;

assign p_out14 = empty_133_fu_190;

assign p_out15 = empty_132_fu_186;

assign p_out16 = empty_131_fu_182;

assign p_out17 = empty_130_fu_178;

assign p_out18 = empty_129_fu_174;

assign p_out19 = empty_128_fu_170;

assign p_out2 = empty_145_fu_250;

assign p_out20 = empty_127_fu_166;

assign p_out21 = empty_126_fu_162;

assign p_out3 = empty_144_fu_246;

assign p_out4 = empty_143_fu_242;

assign p_out5 = empty_142_fu_238;

assign p_out6 = empty_141_fu_222;

assign p_out7 = empty_140_fu_218;

assign p_out8 = empty_139_fu_214;

assign p_out9 = empty_138_fu_210;

assign tmp_20_fu_684_p9 = 'bx;

assign tmp_21_fu_708_p9 = 'bx;

assign trunc_ln39_fu_614_p1 = ap_sig_allocacmp_i_2[1:0];

always @ (posedge ap_clk) begin
    Q_0_load_fu_146[22:0] <= 23'b00000000000000000000000;
    Q_0_load_fu_146[31:30] <= 2'b00;
    Q_1_1_load_fu_150[22:0] <= 23'b00000000000000000000000;
    Q_1_1_load_fu_150[31:30] <= 2'b00;
    Q_2_2_load_fu_154[22:0] <= 23'b00000000000000000000000;
    Q_2_2_load_fu_154[31:30] <= 2'b00;
    Q_3_3_load_fu_158[22:0] <= 23'b00000000000000000000000;
    Q_3_3_load_fu_158[31:30] <= 2'b00;
    Q_2_3_load19_fu_226[22:0] <= 23'b00000000000000000000000;
    Q_2_3_load19_fu_226[31:30] <= 2'b00;
    Q_0_3_load23_fu_230[22:0] <= 23'b00000000000000000000000;
    Q_0_3_load23_fu_230[31:30] <= 2'b00;
    Q_1_3_load27_fu_234[22:0] <= 23'b00000000000000000000000;
    Q_1_3_load27_fu_234[31:30] <= 2'b00;
    empty_142_fu_238[22:0] <= 23'b00000000000000000000000;
    empty_142_fu_238[31:30] <= 2'b00;
    empty_143_fu_242[22:0] <= 23'b00000000000000000000000;
    empty_143_fu_242[31:30] <= 2'b00;
    empty_144_fu_246[22:0] <= 23'b00000000000000000000000;
    empty_144_fu_246[31:30] <= 2'b00;
    empty_145_fu_250[22:0] <= 23'b00000000000000000000000;
    empty_145_fu_250[31:30] <= 2'b00;
    empty_146_fu_254[22:0] <= 23'b00000000000000000000000;
    empty_146_fu_254[31:30] <= 2'b00;
    empty_147_fu_258[22:0] <= 23'b00000000000000000000000;
    empty_147_fu_258[31:30] <= 2'b00;
    Q_3_load31_fu_262[22:0] <= 23'b00000000000000000000000;
    Q_3_load31_fu_262[31:30] <= 2'b00;
    Q_1_load35_fu_266[22:0] <= 23'b00000000000000000000000;
    Q_1_load35_fu_266[31:30] <= 2'b00;
    Q_2_load39_fu_270[22:0] <= 23'b00000000000000000000000;
    Q_2_load39_fu_270[31:30] <= 2'b00;
end

endmodule //top_top_Pipeline_READ_INIT
