-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_top_Pipeline_VITIS_LOOP_181_6_VITIS_LOOP_183_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Q_out_real_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_real_ce0 : OUT STD_LOGIC;
    Q_out_real_we0 : OUT STD_LOGIC;
    Q_out_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_real_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_real_1_ce0 : OUT STD_LOGIC;
    Q_out_real_1_we0 : OUT STD_LOGIC;
    Q_out_real_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_real_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_real_2_ce0 : OUT STD_LOGIC;
    Q_out_real_2_we0 : OUT STD_LOGIC;
    Q_out_real_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_real_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_real_3_ce0 : OUT STD_LOGIC;
    Q_out_real_3_we0 : OUT STD_LOGIC;
    Q_out_real_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_imag_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_imag_ce0 : OUT STD_LOGIC;
    Q_out_imag_we0 : OUT STD_LOGIC;
    Q_out_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_imag_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_imag_1_ce0 : OUT STD_LOGIC;
    Q_out_imag_1_we0 : OUT STD_LOGIC;
    Q_out_imag_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_imag_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_imag_2_ce0 : OUT STD_LOGIC;
    Q_out_imag_2_we0 : OUT STD_LOGIC;
    Q_out_imag_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Q_out_imag_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Q_out_imag_3_ce0 : OUT STD_LOGIC;
    Q_out_imag_3_we0 : OUT STD_LOGIC;
    Q_out_imag_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04303519 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14313528 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24323536 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34333544 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04353552 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14363560 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24373569 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34383577 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04403585 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14413593 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24423601 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34433610 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04453618 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14463626 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24473634 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34483642 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04503651 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14513660 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24523668 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34533676 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04553684 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14563692 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24573701 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34583709 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_05153915 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_15163923 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_25173931 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_35183940 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04603717 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14613726 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24623734 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34633742 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04653750 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14663758 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24673767 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34683775 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04703783 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14713791 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24723799 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34733808 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04753816 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14763824 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24773832 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34783840 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04803849 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14813858 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24823866 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34833874 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_04853882 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_14863890 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_24873899 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_34883907 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_05453948 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_15463956 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_25473964 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_35483973 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of top_top_Pipeline_VITIS_LOOP_181_6_VITIS_LOOP_183_7 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln181_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln181_fu_700_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_184 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln183_fu_1132_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (2 downto 0);
    signal i_fu_188 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln181_1_fu_692_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten40_fu_192 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln181_fu_660_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten40_load : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln183_fu_712_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_fu_884_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_1092_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln183_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln181_1_fu_686_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln181_fu_678_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_716_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_740_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_764_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_788_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_812_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_836_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_860_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_716_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_740_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_764_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_788_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_812_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_836_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_860_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_884_p15 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_924_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_948_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_972_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_996_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_fu_1020_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_fu_1044_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_1068_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_924_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_948_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_972_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_996_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_fu_1020_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_fu_1044_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_1068_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_1092_p15 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_s_fu_716_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_716_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_716_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_716_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_740_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_740_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_740_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_740_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_764_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_764_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_764_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_764_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_788_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_788_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_788_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_788_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_812_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_812_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_812_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_812_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_836_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_836_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_836_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_836_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_fu_860_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_fu_860_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_fu_860_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_fu_860_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_fu_884_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_884_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_884_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_884_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_884_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_884_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_884_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_18_fu_924_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_fu_924_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_fu_924_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_fu_924_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_948_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_948_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_948_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_948_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_972_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_972_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_972_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_972_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_996_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_996_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_996_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_996_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_1020_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_1020_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_1020_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_1020_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_fu_1044_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_fu_1044_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_fu_1044_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_fu_1044_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_1068_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_1068_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_1068_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_1068_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_25_fu_1092_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_25_fu_1092_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_25_fu_1092_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_25_fu_1092_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_25_fu_1092_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_25_fu_1092_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_25_fu_1092_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_sparsemux_15_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_32_1_1_U328 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04303519,
        din1 => mux_case_14313528,
        din2 => mux_case_24323536,
        din3 => mux_case_34333544,
        def => tmp_s_fu_716_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_s_fu_716_p11);

    sparsemux_9_2_32_1_1_U329 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04353552,
        din1 => mux_case_14363560,
        din2 => mux_case_24373569,
        din3 => mux_case_34383577,
        def => tmp_11_fu_740_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_11_fu_740_p11);

    sparsemux_9_2_32_1_1_U330 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04403585,
        din1 => mux_case_14413593,
        din2 => mux_case_24423601,
        din3 => mux_case_34433610,
        def => tmp_12_fu_764_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_12_fu_764_p11);

    sparsemux_9_2_32_1_1_U331 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04453618,
        din1 => mux_case_14463626,
        din2 => mux_case_24473634,
        din3 => mux_case_34483642,
        def => tmp_13_fu_788_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_13_fu_788_p11);

    sparsemux_9_2_32_1_1_U332 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04503651,
        din1 => mux_case_14513660,
        din2 => mux_case_24523668,
        din3 => mux_case_34533676,
        def => tmp_14_fu_812_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_14_fu_812_p11);

    sparsemux_9_2_32_1_1_U333 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04553684,
        din1 => mux_case_14563692,
        din2 => mux_case_24573701,
        din3 => mux_case_34583709,
        def => tmp_15_fu_836_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_15_fu_836_p11);

    sparsemux_9_2_32_1_1_U334 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_05153915,
        din1 => mux_case_15163923,
        din2 => mux_case_25173931,
        din3 => mux_case_35183940,
        def => tmp_16_fu_860_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_16_fu_860_p11);

    sparsemux_15_3_32_1_1_U335 : component top_sparsemux_15_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_s_fu_716_p11,
        din1 => tmp_11_fu_740_p11,
        din2 => tmp_12_fu_764_p11,
        din3 => tmp_13_fu_788_p11,
        din4 => tmp_14_fu_812_p11,
        din5 => tmp_15_fu_836_p11,
        din6 => tmp_16_fu_860_p11,
        def => tmp_17_fu_884_p15,
        sel => select_ln181_1_fu_692_p3,
        dout => tmp_17_fu_884_p17);

    sparsemux_9_2_32_1_1_U336 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04603717,
        din1 => mux_case_14613726,
        din2 => mux_case_24623734,
        din3 => mux_case_34633742,
        def => tmp_18_fu_924_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_18_fu_924_p11);

    sparsemux_9_2_32_1_1_U337 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04653750,
        din1 => mux_case_14663758,
        din2 => mux_case_24673767,
        din3 => mux_case_34683775,
        def => tmp_19_fu_948_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_19_fu_948_p11);

    sparsemux_9_2_32_1_1_U338 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04703783,
        din1 => mux_case_14713791,
        din2 => mux_case_24723799,
        din3 => mux_case_34733808,
        def => tmp_20_fu_972_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_20_fu_972_p11);

    sparsemux_9_2_32_1_1_U339 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04753816,
        din1 => mux_case_14763824,
        din2 => mux_case_24773832,
        din3 => mux_case_34783840,
        def => tmp_21_fu_996_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_21_fu_996_p11);

    sparsemux_9_2_32_1_1_U340 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04803849,
        din1 => mux_case_14813858,
        din2 => mux_case_24823866,
        din3 => mux_case_34833874,
        def => tmp_22_fu_1020_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_22_fu_1020_p11);

    sparsemux_9_2_32_1_1_U341 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_04853882,
        din1 => mux_case_14863890,
        din2 => mux_case_24873899,
        din3 => mux_case_34883907,
        def => tmp_23_fu_1044_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_23_fu_1044_p11);

    sparsemux_9_2_32_1_1_U342 : component top_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => mux_case_05453948,
        din1 => mux_case_15463956,
        din2 => mux_case_25473964,
        din3 => mux_case_35483973,
        def => tmp_24_fu_1068_p9,
        sel => trunc_ln183_fu_712_p1,
        dout => tmp_24_fu_1068_p11);

    sparsemux_15_3_32_1_1_U343 : component top_sparsemux_15_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_18_fu_924_p11,
        din1 => tmp_19_fu_948_p11,
        din2 => tmp_20_fu_972_p11,
        din3 => tmp_21_fu_996_p11,
        din4 => tmp_22_fu_1020_p11,
        din5 => tmp_23_fu_1044_p11,
        din6 => tmp_24_fu_1068_p11,
        def => tmp_25_fu_1092_p15,
        sel => select_ln181_1_fu_692_p3,
        dout => tmp_25_fu_1092_p17);

    flow_control_loop_pipe_sequential_init_U : component top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln181_fu_654_p2 = ap_const_lv1_0)) then 
                    i_fu_188 <= select_ln181_1_fu_692_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_188 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten40_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln181_fu_654_p2 = ap_const_lv1_0)) then 
                    indvar_flatten40_fu_192 <= add_ln181_fu_660_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten40_fu_192 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln181_fu_654_p2 = ap_const_lv1_0)) then 
                    j_fu_184 <= add_ln183_fu_1132_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_184 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Q_out_imag_1_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_imag_1_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_1_ce0 <= ap_const_logic_1;
        else 
            Q_out_imag_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_1_d0 <= tmp_25_fu_1092_p17;

    Q_out_imag_1_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_1_we0 <= ap_const_logic_1;
        else 
            Q_out_imag_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_2_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_imag_2_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_2_ce0 <= ap_const_logic_1;
        else 
            Q_out_imag_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_2_d0 <= tmp_25_fu_1092_p17;

    Q_out_imag_2_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_2_we0 <= ap_const_logic_1;
        else 
            Q_out_imag_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_3_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_imag_3_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_3_ce0 <= ap_const_logic_1;
        else 
            Q_out_imag_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_3_d0 <= tmp_25_fu_1092_p17;

    Q_out_imag_3_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_3_we0 <= ap_const_logic_1;
        else 
            Q_out_imag_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_imag_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_ce0 <= ap_const_logic_1;
        else 
            Q_out_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_imag_d0 <= tmp_25_fu_1092_p17;

    Q_out_imag_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_imag_we0 <= ap_const_logic_1;
        else 
            Q_out_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_1_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_real_1_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_1_ce0 <= ap_const_logic_1;
        else 
            Q_out_real_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_1_d0 <= tmp_17_fu_884_p17;

    Q_out_real_1_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_1_we0 <= ap_const_logic_1;
        else 
            Q_out_real_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_2_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_real_2_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_2_ce0 <= ap_const_logic_1;
        else 
            Q_out_real_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_2_d0 <= tmp_17_fu_884_p17;

    Q_out_real_2_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_2_we0 <= ap_const_logic_1;
        else 
            Q_out_real_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_3_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_real_3_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_3_ce0 <= ap_const_logic_1;
        else 
            Q_out_real_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_3_d0 <= tmp_17_fu_884_p17;

    Q_out_real_3_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_3_we0 <= ap_const_logic_1;
        else 
            Q_out_real_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_address0 <= zext_ln181_fu_700_p1(3 - 1 downto 0);

    Q_out_real_ce0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_ce0 <= ap_const_logic_1;
        else 
            Q_out_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Q_out_real_d0 <= tmp_17_fu_884_p17;

    Q_out_real_we0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2, trunc_ln183_fu_712_p1)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln183_fu_712_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q_out_real_we0 <= ap_const_logic_1;
        else 
            Q_out_real_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln181_1_fu_686_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv3_1));
    add_ln181_fu_660_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten40_load) + unsigned(ap_const_lv5_1));
    add_ln183_fu_1132_p2 <= std_logic_vector(unsigned(select_ln181_fu_678_p3) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln181_fu_654_p2)
    begin
        if (((icmp_ln181_fu_654_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, i_fu_188)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_188;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten40_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten40_fu_192)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten40_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten40_load <= indvar_flatten40_fu_192;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_state1, j_fu_184, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_184;
        end if; 
    end process;

    icmp_ln181_fu_654_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten40_load = ap_const_lv5_1C) else "0";
    icmp_ln183_fu_672_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv3_4) else "0";
    select_ln181_1_fu_692_p3 <= 
        add_ln181_1_fu_686_p2 when (icmp_ln183_fu_672_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln181_fu_678_p3 <= 
        ap_const_lv3_0 when (icmp_ln183_fu_672_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    tmp_11_fu_740_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_12_fu_764_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_13_fu_788_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_14_fu_812_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_15_fu_836_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_16_fu_860_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_17_fu_884_p15 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_18_fu_924_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_19_fu_948_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_20_fu_972_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_21_fu_996_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_22_fu_1020_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_23_fu_1044_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_24_fu_1068_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_25_fu_1092_p15 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_716_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln183_fu_712_p1 <= select_ln181_fu_678_p3(2 - 1 downto 0);
    zext_ln181_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln181_1_fu_692_p3),64));
end behav;
