// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_top_Pipeline_DUMMY_STAGE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Q_real_7_address0,
        Q_real_7_ce0,
        Q_real_7_q0,
        Q_out_real_7_address0,
        Q_out_real_7_ce0,
        Q_out_real_7_we0,
        Q_out_real_7_d0,
        Q_imag_7_address0,
        Q_imag_7_ce0,
        Q_imag_7_q0,
        Q_out_imag_7_address0,
        Q_out_imag_7_ce0,
        Q_out_imag_7_we0,
        Q_out_imag_7_d0,
        Q_real_6_address0,
        Q_real_6_ce0,
        Q_real_6_q0,
        Q_out_real_6_address0,
        Q_out_real_6_ce0,
        Q_out_real_6_we0,
        Q_out_real_6_d0,
        Q_imag_6_address0,
        Q_imag_6_ce0,
        Q_imag_6_q0,
        Q_out_imag_6_address0,
        Q_out_imag_6_ce0,
        Q_out_imag_6_we0,
        Q_out_imag_6_d0,
        Q_real_5_address0,
        Q_real_5_ce0,
        Q_real_5_q0,
        Q_out_real_5_address0,
        Q_out_real_5_ce0,
        Q_out_real_5_we0,
        Q_out_real_5_d0,
        Q_imag_5_address0,
        Q_imag_5_ce0,
        Q_imag_5_q0,
        Q_out_imag_5_address0,
        Q_out_imag_5_ce0,
        Q_out_imag_5_we0,
        Q_out_imag_5_d0,
        Q_real_4_address0,
        Q_real_4_ce0,
        Q_real_4_q0,
        Q_out_real_4_address0,
        Q_out_real_4_ce0,
        Q_out_real_4_we0,
        Q_out_real_4_d0,
        Q_imag_4_address0,
        Q_imag_4_ce0,
        Q_imag_4_q0,
        Q_out_imag_4_address0,
        Q_out_imag_4_ce0,
        Q_out_imag_4_we0,
        Q_out_imag_4_d0,
        Q_real_3_address0,
        Q_real_3_ce0,
        Q_real_3_q0,
        Q_out_real_3_address0,
        Q_out_real_3_ce0,
        Q_out_real_3_we0,
        Q_out_real_3_d0,
        Q_imag_3_address0,
        Q_imag_3_ce0,
        Q_imag_3_q0,
        Q_out_imag_3_address0,
        Q_out_imag_3_ce0,
        Q_out_imag_3_we0,
        Q_out_imag_3_d0,
        Q_real_2_address0,
        Q_real_2_ce0,
        Q_real_2_q0,
        Q_out_real_2_address0,
        Q_out_real_2_ce0,
        Q_out_real_2_we0,
        Q_out_real_2_d0,
        Q_imag_2_address0,
        Q_imag_2_ce0,
        Q_imag_2_q0,
        Q_out_imag_2_address0,
        Q_out_imag_2_ce0,
        Q_out_imag_2_we0,
        Q_out_imag_2_d0,
        Q_real_1_address0,
        Q_real_1_ce0,
        Q_real_1_q0,
        Q_out_real_1_address0,
        Q_out_real_1_ce0,
        Q_out_real_1_we0,
        Q_out_real_1_d0,
        Q_imag_1_address0,
        Q_imag_1_ce0,
        Q_imag_1_q0,
        Q_out_imag_1_address0,
        Q_out_imag_1_ce0,
        Q_out_imag_1_we0,
        Q_out_imag_1_d0,
        add,
        add1,
        Q_out_real_address0,
        Q_out_real_ce0,
        Q_out_real_we0,
        Q_out_real_d0,
        Q_out_imag_address0,
        Q_out_imag_ce0,
        Q_out_imag_we0,
        Q_out_imag_d0,
        R_out_imag_7_address0,
        R_out_imag_7_ce0,
        R_out_imag_7_we0,
        R_out_imag_7_d0,
        R_out_imag_6_address0,
        R_out_imag_6_ce0,
        R_out_imag_6_we0,
        R_out_imag_6_d0,
        R_out_imag_5_address0,
        R_out_imag_5_ce0,
        R_out_imag_5_we0,
        R_out_imag_5_d0,
        R_out_imag_4_address0,
        R_out_imag_4_ce0,
        R_out_imag_4_we0,
        R_out_imag_4_d0,
        R_out_imag_3_address0,
        R_out_imag_3_ce0,
        R_out_imag_3_we0,
        R_out_imag_3_d0,
        R_out_imag_2_address0,
        R_out_imag_2_ce0,
        R_out_imag_2_we0,
        R_out_imag_2_d0,
        R_out_imag_1_address0,
        R_out_imag_1_ce0,
        R_out_imag_1_we0,
        R_out_imag_1_d0,
        R_out_imag_address0,
        R_out_imag_ce0,
        R_out_imag_we0,
        R_out_imag_d0,
        R_out_real_7_address0,
        R_out_real_7_ce0,
        R_out_real_7_we0,
        R_out_real_7_d0,
        R_out_real_6_address0,
        R_out_real_6_ce0,
        R_out_real_6_we0,
        R_out_real_6_d0,
        R_out_real_5_address0,
        R_out_real_5_ce0,
        R_out_real_5_we0,
        R_out_real_5_d0,
        R_out_real_4_address0,
        R_out_real_4_ce0,
        R_out_real_4_we0,
        R_out_real_4_d0,
        R_out_real_3_address0,
        R_out_real_3_ce0,
        R_out_real_3_we0,
        R_out_real_3_d0,
        R_out_real_2_address0,
        R_out_real_2_ce0,
        R_out_real_2_we0,
        R_out_real_2_d0,
        R_out_real_1_address0,
        R_out_real_1_ce0,
        R_out_real_1_we0,
        R_out_real_1_d0,
        R_out_real_address0,
        R_out_real_ce0,
        R_out_real_we0,
        R_out_real_d0,
        R_real_address0,
        R_real_ce0,
        R_real_q0,
        R_real_1_address0,
        R_real_1_ce0,
        R_real_1_q0,
        R_real_2_address0,
        R_real_2_ce0,
        R_real_2_q0,
        R_real_3_address0,
        R_real_3_ce0,
        R_real_3_q0,
        R_real_4_address0,
        R_real_4_ce0,
        R_real_4_q0,
        R_real_5_address0,
        R_real_5_ce0,
        R_real_5_q0,
        R_real_6_address0,
        R_real_6_ce0,
        R_real_6_q0,
        R_real_7_address0,
        R_real_7_ce0,
        R_real_7_q0,
        R_imag_address0,
        R_imag_ce0,
        R_imag_q0,
        R_imag_1_address0,
        R_imag_1_ce0,
        R_imag_1_q0,
        R_imag_2_address0,
        R_imag_2_ce0,
        R_imag_2_q0,
        R_imag_3_address0,
        R_imag_3_ce0,
        R_imag_3_q0,
        R_imag_4_address0,
        R_imag_4_ce0,
        R_imag_4_q0,
        R_imag_5_address0,
        R_imag_5_ce0,
        R_imag_5_q0,
        R_imag_6_address0,
        R_imag_6_ce0,
        R_imag_6_q0,
        R_imag_7_address0,
        R_imag_7_ce0,
        R_imag_7_q0,
        Q_real_address0,
        Q_real_ce0,
        Q_real_q0,
        Q_imag_address0,
        Q_imag_ce0,
        Q_imag_q0,
        add_1,
        add109_1,
        add_2,
        add109_2,
        add_3,
        add109_3,
        add_4,
        add109_4,
        add_5,
        add109_5,
        add_6,
        add109_6,
        add_7,
        add109_7
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] Q_real_7_address0;
output   Q_real_7_ce0;
input  [31:0] Q_real_7_q0;
output  [4:0] Q_out_real_7_address0;
output   Q_out_real_7_ce0;
output   Q_out_real_7_we0;
output  [31:0] Q_out_real_7_d0;
output  [4:0] Q_imag_7_address0;
output   Q_imag_7_ce0;
input  [31:0] Q_imag_7_q0;
output  [4:0] Q_out_imag_7_address0;
output   Q_out_imag_7_ce0;
output   Q_out_imag_7_we0;
output  [31:0] Q_out_imag_7_d0;
output  [4:0] Q_real_6_address0;
output   Q_real_6_ce0;
input  [31:0] Q_real_6_q0;
output  [4:0] Q_out_real_6_address0;
output   Q_out_real_6_ce0;
output   Q_out_real_6_we0;
output  [31:0] Q_out_real_6_d0;
output  [4:0] Q_imag_6_address0;
output   Q_imag_6_ce0;
input  [31:0] Q_imag_6_q0;
output  [4:0] Q_out_imag_6_address0;
output   Q_out_imag_6_ce0;
output   Q_out_imag_6_we0;
output  [31:0] Q_out_imag_6_d0;
output  [4:0] Q_real_5_address0;
output   Q_real_5_ce0;
input  [31:0] Q_real_5_q0;
output  [4:0] Q_out_real_5_address0;
output   Q_out_real_5_ce0;
output   Q_out_real_5_we0;
output  [31:0] Q_out_real_5_d0;
output  [4:0] Q_imag_5_address0;
output   Q_imag_5_ce0;
input  [31:0] Q_imag_5_q0;
output  [4:0] Q_out_imag_5_address0;
output   Q_out_imag_5_ce0;
output   Q_out_imag_5_we0;
output  [31:0] Q_out_imag_5_d0;
output  [4:0] Q_real_4_address0;
output   Q_real_4_ce0;
input  [31:0] Q_real_4_q0;
output  [4:0] Q_out_real_4_address0;
output   Q_out_real_4_ce0;
output   Q_out_real_4_we0;
output  [31:0] Q_out_real_4_d0;
output  [4:0] Q_imag_4_address0;
output   Q_imag_4_ce0;
input  [31:0] Q_imag_4_q0;
output  [4:0] Q_out_imag_4_address0;
output   Q_out_imag_4_ce0;
output   Q_out_imag_4_we0;
output  [31:0] Q_out_imag_4_d0;
output  [4:0] Q_real_3_address0;
output   Q_real_3_ce0;
input  [31:0] Q_real_3_q0;
output  [4:0] Q_out_real_3_address0;
output   Q_out_real_3_ce0;
output   Q_out_real_3_we0;
output  [31:0] Q_out_real_3_d0;
output  [4:0] Q_imag_3_address0;
output   Q_imag_3_ce0;
input  [31:0] Q_imag_3_q0;
output  [4:0] Q_out_imag_3_address0;
output   Q_out_imag_3_ce0;
output   Q_out_imag_3_we0;
output  [31:0] Q_out_imag_3_d0;
output  [4:0] Q_real_2_address0;
output   Q_real_2_ce0;
input  [31:0] Q_real_2_q0;
output  [4:0] Q_out_real_2_address0;
output   Q_out_real_2_ce0;
output   Q_out_real_2_we0;
output  [31:0] Q_out_real_2_d0;
output  [4:0] Q_imag_2_address0;
output   Q_imag_2_ce0;
input  [31:0] Q_imag_2_q0;
output  [4:0] Q_out_imag_2_address0;
output   Q_out_imag_2_ce0;
output   Q_out_imag_2_we0;
output  [31:0] Q_out_imag_2_d0;
output  [4:0] Q_real_1_address0;
output   Q_real_1_ce0;
input  [31:0] Q_real_1_q0;
output  [4:0] Q_out_real_1_address0;
output   Q_out_real_1_ce0;
output   Q_out_real_1_we0;
output  [31:0] Q_out_real_1_d0;
output  [4:0] Q_imag_1_address0;
output   Q_imag_1_ce0;
input  [31:0] Q_imag_1_q0;
output  [4:0] Q_out_imag_1_address0;
output   Q_out_imag_1_ce0;
output   Q_out_imag_1_we0;
output  [31:0] Q_out_imag_1_d0;
input  [31:0] add;
input  [31:0] add1;
output  [4:0] Q_out_real_address0;
output   Q_out_real_ce0;
output   Q_out_real_we0;
output  [31:0] Q_out_real_d0;
output  [4:0] Q_out_imag_address0;
output   Q_out_imag_ce0;
output   Q_out_imag_we0;
output  [31:0] Q_out_imag_d0;
output  [4:0] R_out_imag_7_address0;
output   R_out_imag_7_ce0;
output   R_out_imag_7_we0;
output  [31:0] R_out_imag_7_d0;
output  [4:0] R_out_imag_6_address0;
output   R_out_imag_6_ce0;
output   R_out_imag_6_we0;
output  [31:0] R_out_imag_6_d0;
output  [4:0] R_out_imag_5_address0;
output   R_out_imag_5_ce0;
output   R_out_imag_5_we0;
output  [31:0] R_out_imag_5_d0;
output  [4:0] R_out_imag_4_address0;
output   R_out_imag_4_ce0;
output   R_out_imag_4_we0;
output  [31:0] R_out_imag_4_d0;
output  [4:0] R_out_imag_3_address0;
output   R_out_imag_3_ce0;
output   R_out_imag_3_we0;
output  [31:0] R_out_imag_3_d0;
output  [4:0] R_out_imag_2_address0;
output   R_out_imag_2_ce0;
output   R_out_imag_2_we0;
output  [31:0] R_out_imag_2_d0;
output  [4:0] R_out_imag_1_address0;
output   R_out_imag_1_ce0;
output   R_out_imag_1_we0;
output  [31:0] R_out_imag_1_d0;
output  [4:0] R_out_imag_address0;
output   R_out_imag_ce0;
output   R_out_imag_we0;
output  [31:0] R_out_imag_d0;
output  [4:0] R_out_real_7_address0;
output   R_out_real_7_ce0;
output   R_out_real_7_we0;
output  [31:0] R_out_real_7_d0;
output  [4:0] R_out_real_6_address0;
output   R_out_real_6_ce0;
output   R_out_real_6_we0;
output  [31:0] R_out_real_6_d0;
output  [4:0] R_out_real_5_address0;
output   R_out_real_5_ce0;
output   R_out_real_5_we0;
output  [31:0] R_out_real_5_d0;
output  [4:0] R_out_real_4_address0;
output   R_out_real_4_ce0;
output   R_out_real_4_we0;
output  [31:0] R_out_real_4_d0;
output  [4:0] R_out_real_3_address0;
output   R_out_real_3_ce0;
output   R_out_real_3_we0;
output  [31:0] R_out_real_3_d0;
output  [4:0] R_out_real_2_address0;
output   R_out_real_2_ce0;
output   R_out_real_2_we0;
output  [31:0] R_out_real_2_d0;
output  [4:0] R_out_real_1_address0;
output   R_out_real_1_ce0;
output   R_out_real_1_we0;
output  [31:0] R_out_real_1_d0;
output  [4:0] R_out_real_address0;
output   R_out_real_ce0;
output   R_out_real_we0;
output  [31:0] R_out_real_d0;
output  [4:0] R_real_address0;
output   R_real_ce0;
input  [31:0] R_real_q0;
output  [4:0] R_real_1_address0;
output   R_real_1_ce0;
input  [31:0] R_real_1_q0;
output  [4:0] R_real_2_address0;
output   R_real_2_ce0;
input  [31:0] R_real_2_q0;
output  [4:0] R_real_3_address0;
output   R_real_3_ce0;
input  [31:0] R_real_3_q0;
output  [4:0] R_real_4_address0;
output   R_real_4_ce0;
input  [31:0] R_real_4_q0;
output  [4:0] R_real_5_address0;
output   R_real_5_ce0;
input  [31:0] R_real_5_q0;
output  [4:0] R_real_6_address0;
output   R_real_6_ce0;
input  [31:0] R_real_6_q0;
output  [4:0] R_real_7_address0;
output   R_real_7_ce0;
input  [31:0] R_real_7_q0;
output  [4:0] R_imag_address0;
output   R_imag_ce0;
input  [31:0] R_imag_q0;
output  [4:0] R_imag_1_address0;
output   R_imag_1_ce0;
input  [31:0] R_imag_1_q0;
output  [4:0] R_imag_2_address0;
output   R_imag_2_ce0;
input  [31:0] R_imag_2_q0;
output  [4:0] R_imag_3_address0;
output   R_imag_3_ce0;
input  [31:0] R_imag_3_q0;
output  [4:0] R_imag_4_address0;
output   R_imag_4_ce0;
input  [31:0] R_imag_4_q0;
output  [4:0] R_imag_5_address0;
output   R_imag_5_ce0;
input  [31:0] R_imag_5_q0;
output  [4:0] R_imag_6_address0;
output   R_imag_6_ce0;
input  [31:0] R_imag_6_q0;
output  [4:0] R_imag_7_address0;
output   R_imag_7_ce0;
input  [31:0] R_imag_7_q0;
output  [4:0] Q_real_address0;
output   Q_real_ce0;
input  [31:0] Q_real_q0;
output  [4:0] Q_imag_address0;
output   Q_imag_ce0;
input  [31:0] Q_imag_q0;
input  [31:0] add_1;
input  [31:0] add109_1;
input  [31:0] add_2;
input  [31:0] add109_2;
input  [31:0] add_3;
input  [31:0] add109_3;
input  [31:0] add_4;
input  [31:0] add109_4;
input  [31:0] add_5;
input  [31:0] add109_5;
input  [31:0] add_6;
input  [31:0] add109_6;
input  [31:0] add_7;
input  [31:0] add109_7;

reg ap_idle;
reg Q_real_7_ce0;
reg[4:0] Q_out_real_7_address0;
reg Q_out_real_7_ce0;
reg Q_out_real_7_we0;
reg[31:0] Q_out_real_7_d0;
reg Q_imag_7_ce0;
reg[4:0] Q_out_imag_7_address0;
reg Q_out_imag_7_ce0;
reg Q_out_imag_7_we0;
reg[31:0] Q_out_imag_7_d0;
reg Q_real_6_ce0;
reg[4:0] Q_out_real_6_address0;
reg Q_out_real_6_ce0;
reg Q_out_real_6_we0;
reg[31:0] Q_out_real_6_d0;
reg Q_imag_6_ce0;
reg[4:0] Q_out_imag_6_address0;
reg Q_out_imag_6_ce0;
reg Q_out_imag_6_we0;
reg[31:0] Q_out_imag_6_d0;
reg Q_real_5_ce0;
reg[4:0] Q_out_real_5_address0;
reg Q_out_real_5_ce0;
reg Q_out_real_5_we0;
reg[31:0] Q_out_real_5_d0;
reg Q_imag_5_ce0;
reg[4:0] Q_out_imag_5_address0;
reg Q_out_imag_5_ce0;
reg Q_out_imag_5_we0;
reg[31:0] Q_out_imag_5_d0;
reg Q_real_4_ce0;
reg[4:0] Q_out_real_4_address0;
reg Q_out_real_4_ce0;
reg Q_out_real_4_we0;
reg[31:0] Q_out_real_4_d0;
reg Q_imag_4_ce0;
reg[4:0] Q_out_imag_4_address0;
reg Q_out_imag_4_ce0;
reg Q_out_imag_4_we0;
reg[31:0] Q_out_imag_4_d0;
reg Q_real_3_ce0;
reg[4:0] Q_out_real_3_address0;
reg Q_out_real_3_ce0;
reg Q_out_real_3_we0;
reg[31:0] Q_out_real_3_d0;
reg Q_imag_3_ce0;
reg[4:0] Q_out_imag_3_address0;
reg Q_out_imag_3_ce0;
reg Q_out_imag_3_we0;
reg[31:0] Q_out_imag_3_d0;
reg Q_real_2_ce0;
reg[4:0] Q_out_real_2_address0;
reg Q_out_real_2_ce0;
reg Q_out_real_2_we0;
reg[31:0] Q_out_real_2_d0;
reg Q_imag_2_ce0;
reg[4:0] Q_out_imag_2_address0;
reg Q_out_imag_2_ce0;
reg Q_out_imag_2_we0;
reg[31:0] Q_out_imag_2_d0;
reg Q_real_1_ce0;
reg[4:0] Q_out_real_1_address0;
reg Q_out_real_1_ce0;
reg Q_out_real_1_we0;
reg[31:0] Q_out_real_1_d0;
reg Q_imag_1_ce0;
reg[4:0] Q_out_imag_1_address0;
reg Q_out_imag_1_ce0;
reg Q_out_imag_1_we0;
reg[31:0] Q_out_imag_1_d0;
reg[4:0] Q_out_real_address0;
reg Q_out_real_ce0;
reg Q_out_real_we0;
reg[31:0] Q_out_real_d0;
reg[4:0] Q_out_imag_address0;
reg Q_out_imag_ce0;
reg Q_out_imag_we0;
reg[31:0] Q_out_imag_d0;
reg R_out_imag_7_ce0;
reg R_out_imag_7_we0;
reg R_out_imag_6_ce0;
reg R_out_imag_6_we0;
reg R_out_imag_5_ce0;
reg R_out_imag_5_we0;
reg R_out_imag_4_ce0;
reg R_out_imag_4_we0;
reg R_out_imag_3_ce0;
reg R_out_imag_3_we0;
reg R_out_imag_2_ce0;
reg R_out_imag_2_we0;
reg R_out_imag_1_ce0;
reg R_out_imag_1_we0;
reg R_out_imag_ce0;
reg R_out_imag_we0;
reg R_out_real_7_ce0;
reg R_out_real_7_we0;
reg R_out_real_6_ce0;
reg R_out_real_6_we0;
reg R_out_real_5_ce0;
reg R_out_real_5_we0;
reg R_out_real_4_ce0;
reg R_out_real_4_we0;
reg R_out_real_3_ce0;
reg R_out_real_3_we0;
reg R_out_real_2_ce0;
reg R_out_real_2_we0;
reg R_out_real_1_ce0;
reg R_out_real_1_we0;
reg R_out_real_ce0;
reg R_out_real_we0;
reg R_real_ce0;
reg R_real_1_ce0;
reg R_real_2_ce0;
reg R_real_3_ce0;
reg R_real_4_ce0;
reg R_real_5_ce0;
reg R_real_6_ce0;
reg R_real_7_ce0;
reg R_imag_ce0;
reg R_imag_1_ce0;
reg R_imag_2_ce0;
reg R_imag_3_ce0;
reg R_imag_4_ce0;
reg R_imag_5_ce0;
reg R_imag_6_ce0;
reg R_imag_7_ce0;
reg Q_real_ce0;
reg Q_imag_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln70_fu_1396_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln70_fu_1408_p1;
reg   [63:0] zext_ln70_reg_1588;
reg   [63:0] zext_ln70_reg_1588_pp0_iter1_reg;
reg   [63:0] zext_ln70_reg_1588_pp0_iter2_reg;
reg   [63:0] zext_ln70_reg_1588_pp0_iter3_reg;
wire   [0:0] icmp_ln80_fu_1444_p2;
reg   [0:0] icmp_ln80_reg_1704;
wire   [0:0] icmp_ln80_1_fu_1450_p2;
reg   [0:0] icmp_ln80_1_reg_1718;
wire   [0:0] icmp_ln80_2_fu_1456_p2;
reg   [0:0] icmp_ln80_2_reg_1732;
wire   [0:0] icmp_ln80_3_fu_1462_p2;
reg   [0:0] icmp_ln80_3_reg_1746;
wire   [0:0] icmp_ln80_4_fu_1468_p2;
reg   [0:0] icmp_ln80_4_reg_1760;
wire   [0:0] icmp_ln80_5_fu_1474_p2;
reg   [0:0] icmp_ln80_5_reg_1774;
wire   [0:0] icmp_ln80_6_fu_1480_p2;
reg   [0:0] icmp_ln80_6_reg_1788;
wire   [0:0] icmp_ln80_7_fu_1486_p2;
reg   [0:0] icmp_ln80_7_reg_1802;
reg   [31:0] R_real_load_reg_1816;
reg   [31:0] R_imag_load_reg_1821;
reg   [31:0] R_real_1_load_reg_1826;
reg   [31:0] R_imag_1_load_reg_1831;
reg   [31:0] R_real_2_load_reg_1836;
reg   [31:0] R_imag_2_load_reg_1841;
reg   [31:0] R_real_3_load_reg_1846;
reg   [31:0] R_imag_3_load_reg_1851;
reg   [31:0] R_real_4_load_reg_1856;
reg   [31:0] R_imag_4_load_reg_1861;
reg   [31:0] R_real_5_load_reg_1866;
reg   [31:0] R_imag_5_load_reg_1871;
reg   [31:0] R_real_6_load_reg_1876;
reg   [31:0] R_imag_6_load_reg_1881;
reg   [31:0] R_real_7_load_reg_1886;
reg   [31:0] R_imag_7_load_reg_1891;
wire   [31:0] grp_fu_1308_p2;
reg   [31:0] mul_reg_1896;
wire   [31:0] grp_fu_1313_p2;
reg   [31:0] mul1_reg_1901;
wire   [31:0] grp_fu_1318_p2;
reg   [31:0] mul_1_reg_1906;
wire   [31:0] grp_fu_1323_p2;
reg   [31:0] mul86_1_reg_1911;
wire   [31:0] grp_fu_1328_p2;
reg   [31:0] mul_2_reg_1916;
wire   [31:0] grp_fu_1333_p2;
reg   [31:0] mul86_2_reg_1921;
wire   [31:0] grp_fu_1338_p2;
reg   [31:0] mul_3_reg_1926;
wire   [31:0] grp_fu_1343_p2;
reg   [31:0] mul86_3_reg_1931;
wire   [31:0] grp_fu_1348_p2;
reg   [31:0] mul_4_reg_1936;
wire   [31:0] grp_fu_1353_p2;
reg   [31:0] mul86_4_reg_1941;
wire   [31:0] grp_fu_1358_p2;
reg   [31:0] mul_5_reg_1946;
wire   [31:0] grp_fu_1363_p2;
reg   [31:0] mul86_5_reg_1951;
wire   [31:0] grp_fu_1368_p2;
reg   [31:0] mul_6_reg_1956;
wire   [31:0] grp_fu_1373_p2;
reg   [31:0] mul86_6_reg_1961;
wire   [31:0] grp_fu_1378_p2;
reg   [31:0] mul_7_reg_1966;
wire   [31:0] grp_fu_1383_p2;
reg   [31:0] mul86_7_reg_1971;
wire    ap_block_pp0_stage0;
reg   [4:0] i_fu_216;
wire   [4:0] add_ln70_fu_1402_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_727;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 i_fu_216 = 5'd0;
#0 ap_done_reg = 1'b0;
end

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_load_reg_1816),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1308_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_load_reg_1821),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1313_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_1_load_reg_1826),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1318_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_1_load_reg_1831),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1323_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_2_load_reg_1836),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1328_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_2_load_reg_1841),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1333_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_3_load_reg_1846),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1338_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_3_load_reg_1851),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1343_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_4_load_reg_1856),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1348_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_4_load_reg_1861),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1353_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_5_load_reg_1866),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1358_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_5_load_reg_1871),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1363_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_6_load_reg_1876),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1368_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_6_load_reg_1881),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1373_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_real_7_load_reg_1886),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1378_p2)
);

top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(R_imag_7_load_reg_1891),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_1383_p2)
);

top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln70_fu_1396_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_216 <= add_ln70_fu_1402_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_216 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_1_load_reg_1831 <= R_imag_1_q0;
        R_imag_2_load_reg_1841 <= R_imag_2_q0;
        R_imag_3_load_reg_1851 <= R_imag_3_q0;
        R_imag_4_load_reg_1861 <= R_imag_4_q0;
        R_imag_5_load_reg_1871 <= R_imag_5_q0;
        R_imag_6_load_reg_1881 <= R_imag_6_q0;
        R_imag_7_load_reg_1891 <= R_imag_7_q0;
        R_imag_load_reg_1821 <= R_imag_q0;
        R_real_1_load_reg_1826 <= R_real_1_q0;
        R_real_2_load_reg_1836 <= R_real_2_q0;
        R_real_3_load_reg_1846 <= R_real_3_q0;
        R_real_4_load_reg_1856 <= R_real_4_q0;
        R_real_5_load_reg_1866 <= R_real_5_q0;
        R_real_6_load_reg_1876 <= R_real_6_q0;
        R_real_7_load_reg_1886 <= R_real_7_q0;
        R_real_load_reg_1816 <= R_real_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln80_1_reg_1718 <= icmp_ln80_1_fu_1450_p2;
        icmp_ln80_2_reg_1732 <= icmp_ln80_2_fu_1456_p2;
        icmp_ln80_3_reg_1746 <= icmp_ln80_3_fu_1462_p2;
        icmp_ln80_4_reg_1760 <= icmp_ln80_4_fu_1468_p2;
        icmp_ln80_5_reg_1774 <= icmp_ln80_5_fu_1474_p2;
        icmp_ln80_6_reg_1788 <= icmp_ln80_6_fu_1480_p2;
        icmp_ln80_7_reg_1802 <= icmp_ln80_7_fu_1486_p2;
        icmp_ln80_reg_1704 <= icmp_ln80_fu_1444_p2;
        zext_ln70_reg_1588[4 : 0] <= zext_ln70_fu_1408_p1[4 : 0];
        zext_ln70_reg_1588_pp0_iter1_reg[4 : 0] <= zext_ln70_reg_1588[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        mul1_reg_1901 <= grp_fu_1313_p2;
        mul86_1_reg_1911 <= grp_fu_1323_p2;
        mul86_2_reg_1921 <= grp_fu_1333_p2;
        mul86_3_reg_1931 <= grp_fu_1343_p2;
        mul86_4_reg_1941 <= grp_fu_1353_p2;
        mul86_5_reg_1951 <= grp_fu_1363_p2;
        mul86_6_reg_1961 <= grp_fu_1373_p2;
        mul86_7_reg_1971 <= grp_fu_1383_p2;
        mul_1_reg_1906 <= grp_fu_1318_p2;
        mul_2_reg_1916 <= grp_fu_1328_p2;
        mul_3_reg_1926 <= grp_fu_1338_p2;
        mul_4_reg_1936 <= grp_fu_1348_p2;
        mul_5_reg_1946 <= grp_fu_1358_p2;
        mul_6_reg_1956 <= grp_fu_1368_p2;
        mul_7_reg_1966 <= grp_fu_1378_p2;
        mul_reg_1896 <= grp_fu_1308_p2;
        zext_ln70_reg_1588_pp0_iter2_reg[4 : 0] <= zext_ln70_reg_1588_pp0_iter1_reg[4 : 0];
        zext_ln70_reg_1588_pp0_iter3_reg[4 : 0] <= zext_ln70_reg_1588_pp0_iter2_reg[4 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_1_ce0 = 1'b1;
    end else begin
        Q_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_2_ce0 = 1'b1;
    end else begin
        Q_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_3_ce0 = 1'b1;
    end else begin
        Q_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_4_ce0 = 1'b1;
    end else begin
        Q_imag_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_5_ce0 = 1'b1;
    end else begin
        Q_imag_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_6_ce0 = 1'b1;
    end else begin
        Q_imag_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_7_ce0 = 1'b1;
    end else begin
        Q_imag_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_imag_ce0 = 1'b1;
    end else begin
        Q_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_1_reg_1718 == 1'd1)) begin
            Q_out_imag_1_address0 = 64'd1;
        end else if ((icmp_ln80_1_reg_1718 == 1'd0)) begin
            Q_out_imag_1_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_1_address0 = 'bx;
        end
    end else begin
        Q_out_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_1_reg_1718 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_1_reg_1718 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_1_ce0 = 1'b1;
    end else begin
        Q_out_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_1_reg_1718 == 1'd1)) begin
            Q_out_imag_1_d0 = add109_1;
        end else if ((icmp_ln80_1_reg_1718 == 1'd0)) begin
            Q_out_imag_1_d0 = Q_imag_1_q0;
        end else begin
            Q_out_imag_1_d0 = 'bx;
        end
    end else begin
        Q_out_imag_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_1_reg_1718 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_1_reg_1718 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_1_we0 = 1'b1;
    end else begin
        Q_out_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_2_reg_1732 == 1'd1)) begin
            Q_out_imag_2_address0 = 64'd2;
        end else if ((icmp_ln80_2_reg_1732 == 1'd0)) begin
            Q_out_imag_2_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_2_address0 = 'bx;
        end
    end else begin
        Q_out_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_2_reg_1732 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_2_reg_1732 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_2_ce0 = 1'b1;
    end else begin
        Q_out_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_2_reg_1732 == 1'd1)) begin
            Q_out_imag_2_d0 = add109_2;
        end else if ((icmp_ln80_2_reg_1732 == 1'd0)) begin
            Q_out_imag_2_d0 = Q_imag_2_q0;
        end else begin
            Q_out_imag_2_d0 = 'bx;
        end
    end else begin
        Q_out_imag_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_2_reg_1732 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_2_reg_1732 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_2_we0 = 1'b1;
    end else begin
        Q_out_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_3_reg_1746 == 1'd1)) begin
            Q_out_imag_3_address0 = 64'd3;
        end else if ((icmp_ln80_3_reg_1746 == 1'd0)) begin
            Q_out_imag_3_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_3_address0 = 'bx;
        end
    end else begin
        Q_out_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_3_reg_1746 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_3_reg_1746 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_3_ce0 = 1'b1;
    end else begin
        Q_out_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_3_reg_1746 == 1'd1)) begin
            Q_out_imag_3_d0 = add109_3;
        end else if ((icmp_ln80_3_reg_1746 == 1'd0)) begin
            Q_out_imag_3_d0 = Q_imag_3_q0;
        end else begin
            Q_out_imag_3_d0 = 'bx;
        end
    end else begin
        Q_out_imag_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_3_reg_1746 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_3_reg_1746 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_3_we0 = 1'b1;
    end else begin
        Q_out_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_4_reg_1760 == 1'd1)) begin
            Q_out_imag_4_address0 = 64'd4;
        end else if ((icmp_ln80_4_reg_1760 == 1'd0)) begin
            Q_out_imag_4_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_4_address0 = 'bx;
        end
    end else begin
        Q_out_imag_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_4_reg_1760 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_4_reg_1760 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_4_ce0 = 1'b1;
    end else begin
        Q_out_imag_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_4_reg_1760 == 1'd1)) begin
            Q_out_imag_4_d0 = add109_4;
        end else if ((icmp_ln80_4_reg_1760 == 1'd0)) begin
            Q_out_imag_4_d0 = Q_imag_4_q0;
        end else begin
            Q_out_imag_4_d0 = 'bx;
        end
    end else begin
        Q_out_imag_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_4_reg_1760 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_4_reg_1760 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_4_we0 = 1'b1;
    end else begin
        Q_out_imag_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_5_reg_1774 == 1'd1)) begin
            Q_out_imag_5_address0 = 64'd5;
        end else if ((icmp_ln80_5_reg_1774 == 1'd0)) begin
            Q_out_imag_5_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_5_address0 = 'bx;
        end
    end else begin
        Q_out_imag_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_5_reg_1774 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_5_reg_1774 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_5_ce0 = 1'b1;
    end else begin
        Q_out_imag_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_5_reg_1774 == 1'd1)) begin
            Q_out_imag_5_d0 = add109_5;
        end else if ((icmp_ln80_5_reg_1774 == 1'd0)) begin
            Q_out_imag_5_d0 = Q_imag_5_q0;
        end else begin
            Q_out_imag_5_d0 = 'bx;
        end
    end else begin
        Q_out_imag_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_5_reg_1774 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_5_reg_1774 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_5_we0 = 1'b1;
    end else begin
        Q_out_imag_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_6_reg_1788 == 1'd1)) begin
            Q_out_imag_6_address0 = 64'd6;
        end else if ((icmp_ln80_6_reg_1788 == 1'd0)) begin
            Q_out_imag_6_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_6_address0 = 'bx;
        end
    end else begin
        Q_out_imag_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_6_reg_1788 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_6_reg_1788 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_6_ce0 = 1'b1;
    end else begin
        Q_out_imag_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_6_reg_1788 == 1'd1)) begin
            Q_out_imag_6_d0 = add109_6;
        end else if ((icmp_ln80_6_reg_1788 == 1'd0)) begin
            Q_out_imag_6_d0 = Q_imag_6_q0;
        end else begin
            Q_out_imag_6_d0 = 'bx;
        end
    end else begin
        Q_out_imag_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_6_reg_1788 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_6_reg_1788 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_6_we0 = 1'b1;
    end else begin
        Q_out_imag_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_7_reg_1802 == 1'd1)) begin
            Q_out_imag_7_address0 = 64'd7;
        end else if ((icmp_ln80_7_reg_1802 == 1'd0)) begin
            Q_out_imag_7_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_7_address0 = 'bx;
        end
    end else begin
        Q_out_imag_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_7_reg_1802 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_7_reg_1802 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_7_ce0 = 1'b1;
    end else begin
        Q_out_imag_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_7_reg_1802 == 1'd1)) begin
            Q_out_imag_7_d0 = add109_7;
        end else if ((icmp_ln80_7_reg_1802 == 1'd0)) begin
            Q_out_imag_7_d0 = Q_imag_7_q0;
        end else begin
            Q_out_imag_7_d0 = 'bx;
        end
    end else begin
        Q_out_imag_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_7_reg_1802 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_7_reg_1802 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_7_we0 = 1'b1;
    end else begin
        Q_out_imag_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_reg_1704 == 1'd1)) begin
            Q_out_imag_address0 = 64'd0;
        end else if ((icmp_ln80_reg_1704 == 1'd0)) begin
            Q_out_imag_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_imag_address0 = 'bx;
        end
    end else begin
        Q_out_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_reg_1704 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_reg_1704 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_ce0 = 1'b1;
    end else begin
        Q_out_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_reg_1704 == 1'd1)) begin
            Q_out_imag_d0 = add1;
        end else if ((icmp_ln80_reg_1704 == 1'd0)) begin
            Q_out_imag_d0 = Q_imag_q0;
        end else begin
            Q_out_imag_d0 = 'bx;
        end
    end else begin
        Q_out_imag_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_reg_1704 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_reg_1704 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_imag_we0 = 1'b1;
    end else begin
        Q_out_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_1_reg_1718 == 1'd1)) begin
            Q_out_real_1_address0 = 64'd1;
        end else if ((icmp_ln80_1_reg_1718 == 1'd0)) begin
            Q_out_real_1_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_1_address0 = 'bx;
        end
    end else begin
        Q_out_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_1_reg_1718 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_1_reg_1718 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_1_ce0 = 1'b1;
    end else begin
        Q_out_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_1_reg_1718 == 1'd1)) begin
            Q_out_real_1_d0 = add_1;
        end else if ((icmp_ln80_1_reg_1718 == 1'd0)) begin
            Q_out_real_1_d0 = Q_real_1_q0;
        end else begin
            Q_out_real_1_d0 = 'bx;
        end
    end else begin
        Q_out_real_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_1_reg_1718 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_1_reg_1718 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_1_we0 = 1'b1;
    end else begin
        Q_out_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_2_reg_1732 == 1'd1)) begin
            Q_out_real_2_address0 = 64'd2;
        end else if ((icmp_ln80_2_reg_1732 == 1'd0)) begin
            Q_out_real_2_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_2_address0 = 'bx;
        end
    end else begin
        Q_out_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_2_reg_1732 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_2_reg_1732 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_2_ce0 = 1'b1;
    end else begin
        Q_out_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_2_reg_1732 == 1'd1)) begin
            Q_out_real_2_d0 = add_2;
        end else if ((icmp_ln80_2_reg_1732 == 1'd0)) begin
            Q_out_real_2_d0 = Q_real_2_q0;
        end else begin
            Q_out_real_2_d0 = 'bx;
        end
    end else begin
        Q_out_real_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_2_reg_1732 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_2_reg_1732 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_2_we0 = 1'b1;
    end else begin
        Q_out_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_3_reg_1746 == 1'd1)) begin
            Q_out_real_3_address0 = 64'd3;
        end else if ((icmp_ln80_3_reg_1746 == 1'd0)) begin
            Q_out_real_3_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_3_address0 = 'bx;
        end
    end else begin
        Q_out_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_3_reg_1746 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_3_reg_1746 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_3_ce0 = 1'b1;
    end else begin
        Q_out_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_3_reg_1746 == 1'd1)) begin
            Q_out_real_3_d0 = add_3;
        end else if ((icmp_ln80_3_reg_1746 == 1'd0)) begin
            Q_out_real_3_d0 = Q_real_3_q0;
        end else begin
            Q_out_real_3_d0 = 'bx;
        end
    end else begin
        Q_out_real_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_3_reg_1746 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_3_reg_1746 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_3_we0 = 1'b1;
    end else begin
        Q_out_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_4_reg_1760 == 1'd1)) begin
            Q_out_real_4_address0 = 64'd4;
        end else if ((icmp_ln80_4_reg_1760 == 1'd0)) begin
            Q_out_real_4_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_4_address0 = 'bx;
        end
    end else begin
        Q_out_real_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_4_reg_1760 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_4_reg_1760 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_4_ce0 = 1'b1;
    end else begin
        Q_out_real_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_4_reg_1760 == 1'd1)) begin
            Q_out_real_4_d0 = add_4;
        end else if ((icmp_ln80_4_reg_1760 == 1'd0)) begin
            Q_out_real_4_d0 = Q_real_4_q0;
        end else begin
            Q_out_real_4_d0 = 'bx;
        end
    end else begin
        Q_out_real_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_4_reg_1760 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_4_reg_1760 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_4_we0 = 1'b1;
    end else begin
        Q_out_real_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_5_reg_1774 == 1'd1)) begin
            Q_out_real_5_address0 = 64'd5;
        end else if ((icmp_ln80_5_reg_1774 == 1'd0)) begin
            Q_out_real_5_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_5_address0 = 'bx;
        end
    end else begin
        Q_out_real_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_5_reg_1774 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_5_reg_1774 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_5_ce0 = 1'b1;
    end else begin
        Q_out_real_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_5_reg_1774 == 1'd1)) begin
            Q_out_real_5_d0 = add_5;
        end else if ((icmp_ln80_5_reg_1774 == 1'd0)) begin
            Q_out_real_5_d0 = Q_real_5_q0;
        end else begin
            Q_out_real_5_d0 = 'bx;
        end
    end else begin
        Q_out_real_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_5_reg_1774 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_5_reg_1774 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_5_we0 = 1'b1;
    end else begin
        Q_out_real_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_6_reg_1788 == 1'd1)) begin
            Q_out_real_6_address0 = 64'd6;
        end else if ((icmp_ln80_6_reg_1788 == 1'd0)) begin
            Q_out_real_6_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_6_address0 = 'bx;
        end
    end else begin
        Q_out_real_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_6_reg_1788 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_6_reg_1788 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_6_ce0 = 1'b1;
    end else begin
        Q_out_real_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_6_reg_1788 == 1'd1)) begin
            Q_out_real_6_d0 = add_6;
        end else if ((icmp_ln80_6_reg_1788 == 1'd0)) begin
            Q_out_real_6_d0 = Q_real_6_q0;
        end else begin
            Q_out_real_6_d0 = 'bx;
        end
    end else begin
        Q_out_real_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_6_reg_1788 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_6_reg_1788 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_6_we0 = 1'b1;
    end else begin
        Q_out_real_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_7_reg_1802 == 1'd1)) begin
            Q_out_real_7_address0 = 64'd7;
        end else if ((icmp_ln80_7_reg_1802 == 1'd0)) begin
            Q_out_real_7_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_7_address0 = 'bx;
        end
    end else begin
        Q_out_real_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_7_reg_1802 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_7_reg_1802 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_7_ce0 = 1'b1;
    end else begin
        Q_out_real_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_7_reg_1802 == 1'd1)) begin
            Q_out_real_7_d0 = add_7;
        end else if ((icmp_ln80_7_reg_1802 == 1'd0)) begin
            Q_out_real_7_d0 = Q_real_7_q0;
        end else begin
            Q_out_real_7_d0 = 'bx;
        end
    end else begin
        Q_out_real_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_7_reg_1802 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_7_reg_1802 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_7_we0 = 1'b1;
    end else begin
        Q_out_real_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_reg_1704 == 1'd1)) begin
            Q_out_real_address0 = 64'd0;
        end else if ((icmp_ln80_reg_1704 == 1'd0)) begin
            Q_out_real_address0 = zext_ln70_reg_1588;
        end else begin
            Q_out_real_address0 = 'bx;
        end
    end else begin
        Q_out_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_reg_1704 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_reg_1704 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_ce0 = 1'b1;
    end else begin
        Q_out_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_727)) begin
        if ((icmp_ln80_reg_1704 == 1'd1)) begin
            Q_out_real_d0 = add;
        end else if ((icmp_ln80_reg_1704 == 1'd0)) begin
            Q_out_real_d0 = Q_real_q0;
        end else begin
            Q_out_real_d0 = 'bx;
        end
    end else begin
        Q_out_real_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln80_reg_1704 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln80_reg_1704 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        Q_out_real_we0 = 1'b1;
    end else begin
        Q_out_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_1_ce0 = 1'b1;
    end else begin
        Q_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_2_ce0 = 1'b1;
    end else begin
        Q_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_3_ce0 = 1'b1;
    end else begin
        Q_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_4_ce0 = 1'b1;
    end else begin
        Q_real_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_5_ce0 = 1'b1;
    end else begin
        Q_real_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_6_ce0 = 1'b1;
    end else begin
        Q_real_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_7_ce0 = 1'b1;
    end else begin
        Q_real_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Q_real_ce0 = 1'b1;
    end else begin
        Q_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_1_ce0 = 1'b1;
    end else begin
        R_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_2_ce0 = 1'b1;
    end else begin
        R_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_3_ce0 = 1'b1;
    end else begin
        R_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_4_ce0 = 1'b1;
    end else begin
        R_imag_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_5_ce0 = 1'b1;
    end else begin
        R_imag_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_6_ce0 = 1'b1;
    end else begin
        R_imag_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_7_ce0 = 1'b1;
    end else begin
        R_imag_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_imag_ce0 = 1'b1;
    end else begin
        R_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_1_ce0 = 1'b1;
    end else begin
        R_out_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_1_we0 = 1'b1;
    end else begin
        R_out_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_2_ce0 = 1'b1;
    end else begin
        R_out_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_2_we0 = 1'b1;
    end else begin
        R_out_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_3_ce0 = 1'b1;
    end else begin
        R_out_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_3_we0 = 1'b1;
    end else begin
        R_out_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_4_ce0 = 1'b1;
    end else begin
        R_out_imag_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_4_we0 = 1'b1;
    end else begin
        R_out_imag_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_5_ce0 = 1'b1;
    end else begin
        R_out_imag_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_5_we0 = 1'b1;
    end else begin
        R_out_imag_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_6_ce0 = 1'b1;
    end else begin
        R_out_imag_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_6_we0 = 1'b1;
    end else begin
        R_out_imag_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_7_ce0 = 1'b1;
    end else begin
        R_out_imag_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_7_we0 = 1'b1;
    end else begin
        R_out_imag_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_ce0 = 1'b1;
    end else begin
        R_out_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_imag_we0 = 1'b1;
    end else begin
        R_out_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_1_ce0 = 1'b1;
    end else begin
        R_out_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_1_we0 = 1'b1;
    end else begin
        R_out_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_2_ce0 = 1'b1;
    end else begin
        R_out_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_2_we0 = 1'b1;
    end else begin
        R_out_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_3_ce0 = 1'b1;
    end else begin
        R_out_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_3_we0 = 1'b1;
    end else begin
        R_out_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_4_ce0 = 1'b1;
    end else begin
        R_out_real_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_4_we0 = 1'b1;
    end else begin
        R_out_real_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_5_ce0 = 1'b1;
    end else begin
        R_out_real_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_5_we0 = 1'b1;
    end else begin
        R_out_real_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_6_ce0 = 1'b1;
    end else begin
        R_out_real_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_6_we0 = 1'b1;
    end else begin
        R_out_real_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_7_ce0 = 1'b1;
    end else begin
        R_out_real_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_7_we0 = 1'b1;
    end else begin
        R_out_real_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_ce0 = 1'b1;
    end else begin
        R_out_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        R_out_real_we0 = 1'b1;
    end else begin
        R_out_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_1_ce0 = 1'b1;
    end else begin
        R_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_2_ce0 = 1'b1;
    end else begin
        R_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_3_ce0 = 1'b1;
    end else begin
        R_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_4_ce0 = 1'b1;
    end else begin
        R_real_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_5_ce0 = 1'b1;
    end else begin
        R_real_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_6_ce0 = 1'b1;
    end else begin
        R_real_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_7_ce0 = 1'b1;
    end else begin
        R_real_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_real_ce0 = 1'b1;
    end else begin
        R_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_1396_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_216;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Q_imag_1_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_2_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_3_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_4_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_5_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_6_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_7_address0 = zext_ln70_fu_1408_p1;

assign Q_imag_address0 = zext_ln70_fu_1408_p1;

assign Q_real_1_address0 = zext_ln70_fu_1408_p1;

assign Q_real_2_address0 = zext_ln70_fu_1408_p1;

assign Q_real_3_address0 = zext_ln70_fu_1408_p1;

assign Q_real_4_address0 = zext_ln70_fu_1408_p1;

assign Q_real_5_address0 = zext_ln70_fu_1408_p1;

assign Q_real_6_address0 = zext_ln70_fu_1408_p1;

assign Q_real_7_address0 = zext_ln70_fu_1408_p1;

assign Q_real_address0 = zext_ln70_fu_1408_p1;

assign R_imag_1_address0 = zext_ln70_fu_1408_p1;

assign R_imag_2_address0 = zext_ln70_fu_1408_p1;

assign R_imag_3_address0 = zext_ln70_fu_1408_p1;

assign R_imag_4_address0 = zext_ln70_fu_1408_p1;

assign R_imag_5_address0 = zext_ln70_fu_1408_p1;

assign R_imag_6_address0 = zext_ln70_fu_1408_p1;

assign R_imag_7_address0 = zext_ln70_fu_1408_p1;

assign R_imag_address0 = zext_ln70_fu_1408_p1;

assign R_out_imag_1_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_1_d0 = mul86_1_reg_1911;

assign R_out_imag_2_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_2_d0 = mul86_2_reg_1921;

assign R_out_imag_3_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_3_d0 = mul86_3_reg_1931;

assign R_out_imag_4_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_4_d0 = mul86_4_reg_1941;

assign R_out_imag_5_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_5_d0 = mul86_5_reg_1951;

assign R_out_imag_6_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_6_d0 = mul86_6_reg_1961;

assign R_out_imag_7_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_7_d0 = mul86_7_reg_1971;

assign R_out_imag_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_imag_d0 = mul1_reg_1901;

assign R_out_real_1_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_1_d0 = mul_1_reg_1906;

assign R_out_real_2_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_2_d0 = mul_2_reg_1916;

assign R_out_real_3_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_3_d0 = mul_3_reg_1926;

assign R_out_real_4_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_4_d0 = mul_4_reg_1936;

assign R_out_real_5_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_5_d0 = mul_5_reg_1946;

assign R_out_real_6_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_6_d0 = mul_6_reg_1956;

assign R_out_real_7_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_7_d0 = mul_7_reg_1966;

assign R_out_real_address0 = zext_ln70_reg_1588_pp0_iter3_reg;

assign R_out_real_d0 = mul_reg_1896;

assign R_real_1_address0 = zext_ln70_fu_1408_p1;

assign R_real_2_address0 = zext_ln70_fu_1408_p1;

assign R_real_3_address0 = zext_ln70_fu_1408_p1;

assign R_real_4_address0 = zext_ln70_fu_1408_p1;

assign R_real_5_address0 = zext_ln70_fu_1408_p1;

assign R_real_6_address0 = zext_ln70_fu_1408_p1;

assign R_real_7_address0 = zext_ln70_fu_1408_p1;

assign R_real_address0 = zext_ln70_fu_1408_p1;

assign add_ln70_fu_1402_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_727 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln70_fu_1396_p2 = ((ap_sig_allocacmp_i_1 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln80_1_fu_1450_p2 = ((ap_sig_allocacmp_i_1 == 5'd1) ? 1'b1 : 1'b0);

assign icmp_ln80_2_fu_1456_p2 = ((ap_sig_allocacmp_i_1 == 5'd2) ? 1'b1 : 1'b0);

assign icmp_ln80_3_fu_1462_p2 = ((ap_sig_allocacmp_i_1 == 5'd3) ? 1'b1 : 1'b0);

assign icmp_ln80_4_fu_1468_p2 = ((ap_sig_allocacmp_i_1 == 5'd4) ? 1'b1 : 1'b0);

assign icmp_ln80_5_fu_1474_p2 = ((ap_sig_allocacmp_i_1 == 5'd5) ? 1'b1 : 1'b0);

assign icmp_ln80_6_fu_1480_p2 = ((ap_sig_allocacmp_i_1 == 5'd6) ? 1'b1 : 1'b0);

assign icmp_ln80_7_fu_1486_p2 = ((ap_sig_allocacmp_i_1 == 5'd7) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_1444_p2 = ((ap_sig_allocacmp_i_1 == 5'd0) ? 1'b1 : 1'b0);

assign zext_ln70_fu_1408_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln70_reg_1588[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln70_reg_1588_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln70_reg_1588_pp0_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln70_reg_1588_pp0_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_top_Pipeline_DUMMY_STAGE
