-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_qr_top_qr_Pipeline_READ_A_OUTER_READ_A_INNER is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_AWREADY : IN STD_LOGIC;
    m_axi_gmem_A_REAL_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_A_REAL_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_REAL_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_REAL_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_REAL_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_REAL_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_REAL_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_WVALID : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_WREADY : IN STD_LOGIC;
    m_axi_gmem_A_REAL_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_REAL_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_WLAST : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_ARREADY : IN STD_LOGIC;
    m_axi_gmem_A_REAL_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_A_REAL_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_REAL_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_REAL_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_REAL_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_REAL_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_REAL_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_REAL_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_RVALID : IN STD_LOGIC;
    m_axi_gmem_A_REAL_RREADY : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_REAL_RLAST : IN STD_LOGIC;
    m_axi_gmem_A_REAL_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_A_REAL_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_REAL_BVALID : IN STD_LOGIC;
    m_axi_gmem_A_REAL_BREADY : OUT STD_LOGIC;
    m_axi_gmem_A_REAL_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_REAL_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_REAL_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_A_IMAG_AWREADY : IN STD_LOGIC;
    m_axi_gmem_A_IMAG_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_A_IMAG_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_IMAG_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_IMAG_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_IMAG_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_IMAG_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_IMAG_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_WVALID : OUT STD_LOGIC;
    m_axi_gmem_A_IMAG_WREADY : IN STD_LOGIC;
    m_axi_gmem_A_IMAG_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_IMAG_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_WLAST : OUT STD_LOGIC;
    m_axi_gmem_A_IMAG_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_A_IMAG_ARREADY : IN STD_LOGIC;
    m_axi_gmem_A_IMAG_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_A_IMAG_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_IMAG_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_IMAG_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_IMAG_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_IMAG_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_IMAG_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_IMAG_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_RVALID : IN STD_LOGIC;
    m_axi_gmem_A_IMAG_RREADY : OUT STD_LOGIC;
    m_axi_gmem_A_IMAG_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_A_IMAG_RLAST : IN STD_LOGIC;
    m_axi_gmem_A_IMAG_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_A_IMAG_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_IMAG_BVALID : IN STD_LOGIC;
    m_axi_gmem_A_IMAG_BREADY : OUT STD_LOGIC;
    m_axi_gmem_A_IMAG_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_IMAG_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_A_IMAG_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln274 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln274_1 : IN STD_LOGIC_VECTOR (61 downto 0);
    A_local_imag_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_imag_3_ce0 : OUT STD_LOGIC;
    A_local_imag_3_we0 : OUT STD_LOGIC;
    A_local_imag_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_imag_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_imag_2_ce0 : OUT STD_LOGIC;
    A_local_imag_2_we0 : OUT STD_LOGIC;
    A_local_imag_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_imag_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_imag_1_ce0 : OUT STD_LOGIC;
    A_local_imag_1_we0 : OUT STD_LOGIC;
    A_local_imag_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_imag_ce0 : OUT STD_LOGIC;
    A_local_imag_we0 : OUT STD_LOGIC;
    A_local_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_real_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_real_3_ce0 : OUT STD_LOGIC;
    A_local_real_3_we0 : OUT STD_LOGIC;
    A_local_real_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_real_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_real_2_ce0 : OUT STD_LOGIC;
    A_local_real_2_we0 : OUT STD_LOGIC;
    A_local_real_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_real_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_real_1_ce0 : OUT STD_LOGIC;
    A_local_real_1_we0 : OUT STD_LOGIC;
    A_local_real_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_local_real_ce0 : OUT STD_LOGIC;
    A_local_real_we0 : OUT STD_LOGIC;
    A_local_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of top_qr_top_qr_Pipeline_READ_A_OUTER_READ_A_INNER is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_C8 : STD_LOGIC_VECTOR (7 downto 0) := "11001000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln274_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_A_IMAG_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem_A_REAL_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal gmem_A_REAL_addr_read_reg_420 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_A_IMAG_addr_read_reg_425 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln279_fu_343_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_96 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln275_fu_369_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_100 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln274_1_fu_315_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_104 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln274_fu_266_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln275_fu_323_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal bitcast_ln279_fu_355_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln280_fu_362_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln275_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln274_1_fu_309_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln274_fu_301_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_327_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln_fu_335_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_qr_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component top_qr_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    i_fu_100 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    i_fu_100 <= select_ln274_1_fu_315_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln274_fu_260_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_104 <= add_ln274_fu_266_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_104 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    j_fu_96 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    j_fu_96 <= add_ln275_fu_369_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                gmem_A_IMAG_addr_read_reg_425 <= m_axi_gmem_A_IMAG_RDATA;
                gmem_A_REAL_addr_read_reg_420 <= m_axi_gmem_A_REAL_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_local_imag_1_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_imag_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_1_ce0 <= ap_const_logic_1;
        else 
            A_local_imag_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_1_d0 <= bitcast_ln280_fu_362_p1;

    A_local_imag_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_1_we0 <= ap_const_logic_1;
        else 
            A_local_imag_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_2_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_imag_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_2_ce0 <= ap_const_logic_1;
        else 
            A_local_imag_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_2_d0 <= bitcast_ln280_fu_362_p1;

    A_local_imag_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_2_we0 <= ap_const_logic_1;
        else 
            A_local_imag_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_3_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_imag_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_3_ce0 <= ap_const_logic_1;
        else 
            A_local_imag_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_3_d0 <= bitcast_ln280_fu_362_p1;

    A_local_imag_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_3_we0 <= ap_const_logic_1;
        else 
            A_local_imag_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_imag_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_ce0 <= ap_const_logic_1;
        else 
            A_local_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_imag_d0 <= bitcast_ln280_fu_362_p1;

    A_local_imag_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_imag_we0 <= ap_const_logic_1;
        else 
            A_local_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_1_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_real_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_1_ce0 <= ap_const_logic_1;
        else 
            A_local_real_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_1_d0 <= bitcast_ln279_fu_355_p1;

    A_local_real_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_1_we0 <= ap_const_logic_1;
        else 
            A_local_real_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_2_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_real_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_2_ce0 <= ap_const_logic_1;
        else 
            A_local_real_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_2_d0 <= bitcast_ln279_fu_355_p1;

    A_local_real_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_2_we0 <= ap_const_logic_1;
        else 
            A_local_real_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_3_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_real_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_3_ce0 <= ap_const_logic_1;
        else 
            A_local_real_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_3_d0 <= bitcast_ln279_fu_355_p1;

    A_local_real_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_3_we0 <= ap_const_logic_1;
        else 
            A_local_real_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_address0 <= zext_ln279_fu_343_p1(6 - 1 downto 0);

    A_local_real_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_ce0 <= ap_const_logic_1;
        else 
            A_local_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_real_d0 <= bitcast_ln279_fu_355_p1;

    A_local_real_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln275_fu_323_p1)
    begin
        if (((trunc_ln275_fu_323_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_real_we0 <= ap_const_logic_1;
        else 
            A_local_real_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln274_1_fu_309_p2 <= std_logic_vector(unsigned(i_fu_100) + unsigned(ap_const_lv5_1));
    add_ln274_fu_266_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv8_1));
    add_ln275_fu_369_p2 <= std_logic_vector(unsigned(select_ln274_fu_301_p3) + unsigned(ap_const_lv4_1));
    add_ln_fu_335_p3 <= (select_ln274_1_fu_315_p3 & tmp_fu_327_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_A_REAL_RVALID, m_axi_gmem_A_IMAG_RVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((m_axi_gmem_A_REAL_RVALID = ap_const_logic_0) or (m_axi_gmem_A_IMAG_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln274_fu_260_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln274_fu_260_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_104)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_104;
        end if; 
    end process;

    bitcast_ln279_fu_355_p1 <= gmem_A_REAL_addr_read_reg_420;
    bitcast_ln280_fu_362_p1 <= gmem_A_IMAG_addr_read_reg_425;

    gmem_A_IMAG_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_A_IMAG_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_A_IMAG_blk_n_R <= m_axi_gmem_A_IMAG_RVALID;
        else 
            gmem_A_IMAG_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem_A_REAL_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_A_REAL_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_A_REAL_blk_n_R <= m_axi_gmem_A_REAL_RVALID;
        else 
            gmem_A_REAL_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln274_fu_260_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv8_C8) else "0";
    icmp_ln275_fu_295_p2 <= "1" when (j_fu_96 = ap_const_lv4_8) else "0";
    m_axi_gmem_A_IMAG_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_A_IMAG_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_A_IMAG_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_ARID <= ap_const_lv1_0;
    m_axi_gmem_A_IMAG_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_A_IMAG_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_A_IMAG_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_A_IMAG_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_A_IMAG_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_A_IMAG_ARVALID <= ap_const_logic_0;
    m_axi_gmem_A_IMAG_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_A_IMAG_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_A_IMAG_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_AWID <= ap_const_lv1_0;
    m_axi_gmem_A_IMAG_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_A_IMAG_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_A_IMAG_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_A_IMAG_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_A_IMAG_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_A_IMAG_AWVALID <= ap_const_logic_0;
    m_axi_gmem_A_IMAG_BREADY <= ap_const_logic_0;

    m_axi_gmem_A_IMAG_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_A_IMAG_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_A_IMAG_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_A_IMAG_WDATA <= ap_const_lv32_0;
    m_axi_gmem_A_IMAG_WID <= ap_const_lv1_0;
    m_axi_gmem_A_IMAG_WLAST <= ap_const_logic_0;
    m_axi_gmem_A_IMAG_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_A_IMAG_WUSER <= ap_const_lv1_0;
    m_axi_gmem_A_IMAG_WVALID <= ap_const_logic_0;
    m_axi_gmem_A_REAL_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_A_REAL_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_A_REAL_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_ARID <= ap_const_lv1_0;
    m_axi_gmem_A_REAL_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_A_REAL_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_A_REAL_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_A_REAL_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_A_REAL_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_A_REAL_ARVALID <= ap_const_logic_0;
    m_axi_gmem_A_REAL_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_A_REAL_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_A_REAL_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_AWID <= ap_const_lv1_0;
    m_axi_gmem_A_REAL_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_A_REAL_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_A_REAL_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_A_REAL_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_A_REAL_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_A_REAL_AWVALID <= ap_const_logic_0;
    m_axi_gmem_A_REAL_BREADY <= ap_const_logic_0;

    m_axi_gmem_A_REAL_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_A_REAL_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_A_REAL_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_A_REAL_WDATA <= ap_const_lv32_0;
    m_axi_gmem_A_REAL_WID <= ap_const_lv1_0;
    m_axi_gmem_A_REAL_WLAST <= ap_const_logic_0;
    m_axi_gmem_A_REAL_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_A_REAL_WUSER <= ap_const_lv1_0;
    m_axi_gmem_A_REAL_WVALID <= ap_const_logic_0;
    select_ln274_1_fu_315_p3 <= 
        add_ln274_1_fu_309_p2 when (icmp_ln275_fu_295_p2(0) = '1') else 
        i_fu_100;
    select_ln274_fu_301_p3 <= 
        ap_const_lv4_0 when (icmp_ln275_fu_295_p2(0) = '1') else 
        j_fu_96;
    tmp_fu_327_p3 <= select_ln274_fu_301_p3(2 downto 2);
    trunc_ln275_fu_323_p1 <= select_ln274_fu_301_p3(2 - 1 downto 0);
    zext_ln279_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_335_p3),64));
end behav;
